package modelbuild_test

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/arandu-io/aru/internal/gen"
	"github.com/arandu-io/aru/internal/modelbuild"
)

const user = `package models

import "github.com/arandu-io/hesape/database/model"

type User struct {
	model.Model

	ID       string ` + "`db:\"id\"`" + `
	TenantID string ` + "`db:\"tenant_id\"`" + `
	Name     string ` + "`db:\"name\"`" + `
}

var userTable = model.NewTable(model.TableSpec{
	Name:      "users",
	New:       func() model.Entity { return new(User) },
	UniqueIDs: true,
})
`

const post = `package models

import hm "github.com/arandu-io/hesape/database/model"

type Post struct {
	hm.Model

	ID    string ` + "`db:\"id\"`" + `
	Title string ` + "`db:\"title\"`" + `
}

var posts = hm.NewTable(hm.TableSpec{
	Name:        "posts",
	New:         func() hm.Entity { return &Post{} },
	SoftDeletes: true,
})
`

// TestAModuleWithNoEntityHasNothingToBuild: a project on the generic model, or
// with no model at all, gets no file and no error.
func TestAModuleWithNoEntityHasNothingToBuild(t *testing.T) {
	root := module(t, map[string]string{
		"app/Models/User.go": `package models

import "github.com/arandu-io/hesape/database/model"

type User struct {
	model.Model[User]
	ID string
}
`,
		"main.go": "package main\n\nfunc main() {}\n",
	})
	changes := plan(t, root)
	if len(changes) != 0 {
		t.Fatalf("a module with no entity on the core plans %v", changes)
	}
}

// TestEveryEntityGetsItsQueryBesideIt finds the struct and its table however
// the import is named and however the row is allocated, and writes one file per
// entity -- the soft-delete methods only where the spec asks for them. A second
// plan after applying the first is empty, which is what --check relies on.
func TestEveryEntityGetsItsQueryBesideIt(t *testing.T) {
	root := module(t, map[string]string{"app/Models/User.go": user, "app/Models/Post.go": post})

	changes := plan(t, root)
	if got := paths(changes); got != "app/Models/PostQuery.go app/Models/UserQuery.go" {
		t.Fatalf("planned %s", got)
	}
	for _, c := range changes {
		if c.Why != "missing" {
			t.Errorf("%s is %s, want missing", c.Path, c.Why)
		}
	}
	if err := modelbuild.Apply(root, changes); err != nil {
		t.Fatal(err)
	}

	postQuery := read(t, root, "app/Models/PostQuery.go")
	for _, want := range []string{
		"// Code generated by aru model:build from Post.go. DO NOT EDIT.",
		"func Posts(db model.DB) *PostQuery { return &PostQuery{b: posts.Query(db)} }",
		"func (q *PostQuery) WithTrashed(",
	} {
		if !strings.Contains(postQuery, want) {
			t.Errorf("PostQuery.go does not contain %q", want)
		}
	}
	if strings.Contains(read(t, root, "app/Models/UserQuery.go"), "WithTrashed") {
		t.Error("a table that does not soft delete got the soft-delete methods")
	}

	if again := plan(t, root); len(again) != 0 {
		t.Errorf("a second plan after applying the first is not empty: %v", again)
	}

	// An edit to the generated file is stale; a column added to the entity is
	// not, because the query file depends on no field.
	write(t, root, "app/Models/UserQuery.go", read(t, root, "app/Models/UserQuery.go")+"\n// edited\n")
	write(t, root, "app/Models/Post.go", strings.Replace(post, "Title string", "Body string `db:\"body\"`\n\tTitle string", 1))
	if got := plan(t, root); paths(got) != "app/Models/UserQuery.go" || got[0].Why != "stale" {
		t.Errorf("planned %v, want the edited UserQuery.go as stale and nothing else", got)
	}
}

// TestAQueryWhoseEntityIsGoneIsRemoved, and only a file model:build wrote: a
// hand-written file whose name merely looks like one stays.
func TestAQueryWhoseEntityIsGoneIsRemoved(t *testing.T) {
	root := module(t, map[string]string{"app/Models/User.go": user, "app/Models/Post.go": post})
	if err := modelbuild.Apply(root, plan(t, root)); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(filepath.Join(root, "app/Models/Post.go")); err != nil {
		t.Fatal(err)
	}
	write(t, root, "app/Models/ReportQuery.go", "package models\n\n// ReportQuery is written by hand.\ntype ReportQuery struct{}\n")

	changes := plan(t, root)
	if paths(changes) != "app/Models/PostQuery.go" || changes[0].Content != nil || changes[0].Why != "orphaned" {
		t.Fatalf("planned %v, want PostQuery.go removed and nothing else", changes)
	}
}

// TestAPlainModuleRootIsBuiltToo: a module that ships entities has no app/ and
// no arandu.toml, and its package is wherever it is.
func TestAPlainModuleRootIsBuiltToo(t *testing.T) {
	root := module(t, map[string]string{"store/User.go": strings.Replace(user, "package models", "package store", 1)})
	changes := plan(t, root)
	if paths(changes) != "store/UserQuery.go" {
		t.Fatalf("planned %s", paths(changes))
	}
	if !strings.Contains(string(changes[0].Content), "\npackage store\n") {
		t.Error("the query file does not carry the entity's package clause")
	}
}

// TestWhatCannotBeGeneratedFromIsRefusedAtItsLine: a struct with no table, a
// table read from somewhere model:build cannot see, a name the package already
// uses, and a file in the way that model:build did not write.
func TestWhatCannotBeGeneratedFromIsRefusedAtItsLine(t *testing.T) {
	for _, c := range []struct {
		name  string
		files map[string]string
		at    string
		says  string
	}{
		{
			"no table",
			map[string]string{"app/Models/User.go": strings.SplitN(user, "var userTable", 2)[0]},
			"app/Models/User.go:5", "no model.NewTable in its package allocates it",
		},
		{
			"soft deletes not a literal",
			map[string]string{"app/Models/User.go": strings.Replace(user, "UniqueIDs: true,", "UniqueIDs: true,\n\tSoftDeletes: soft,", 1) + "\nconst soft = true\n"},
			"app/Models/User.go:17", "not the word true or false",
		},
		{
			"a name the query declares",
			map[string]string{"app/Models/User.go": user + "\nfunc Users() {}\n"},
			"app/Models/User.go:5", "already declares it",
		},
		{
			"a file in the way",
			map[string]string{"app/Models/User.go": user, "app/Models/UserQuery.go": "package models\n"},
			"app/Models/UserQuery.go:1", "model:build did not write it",
		},
	} {
		t.Run(c.name, func(t *testing.T) {
			_, err := modelbuild.Plan(module(t, c.files))
			var refused *modelbuild.Error
			if !errors.As(err, &refused) {
				t.Fatalf("Plan returned %v, want a refusal at a line", err)
			}
			if !strings.HasPrefix(err.Error(), c.at+":") || !strings.Contains(err.Error(), c.says) {
				t.Errorf("refusal = %q, want it at %s saying %q", err, c.at, c.says)
			}
		})
	}
}

// TestAFactoryModelBuildRenderedIsRenderedAgain keeps its custom block -- the
// default state and the named states -- and follows the entity everywhere
// else. A factory written against the generic model is left alone: its default
// state is outside any custom block, and rewriting it would delete it.
func TestAFactoryModelBuildRenderedIsRenderedAgain(t *testing.T) {
	root := module(t, map[string]string{"app/Models/User.go": user})
	factory, err := gen.RenderFactory(gen.FactorySpec{
		Entity: "User", Tenant: true, Fields: []gen.FactoryField{{GoName: "Name", GoType: "string"}},
		ModelsImport: "example.test/project/app/Models",
	})
	if err != nil {
		t.Fatal(err)
	}
	// The person's edit: a default state that uses a package, imported where
	// imports go, which is outside the custom block.
	edited := strings.Replace(string(factory.Content), "Name: f.UserName(),", `Name: strings.ToUpper(f.UserName()),`, 1)
	edited = strings.Replace(edited, "\t\"context\"\n", "\t\"context\"\n\t\"strings\"\n", 1)
	// The generated half drifted: a method somebody deleted by hand.
	edited = strings.Replace(edited, "// Seed returns a factory whose values start from seed.\n", "", 1)
	write(t, root, "database/factories/UserFactory.go", edited)
	write(t, root, "database/factories/PostFactory.go", "package factories\n\n// written against the generic model\n")

	changes := plan(t, root)
	if paths(changes) != "app/Models/UserQuery.go database/factories/UserFactory.go" {
		t.Fatalf("planned %s", paths(changes))
	}
	got := string(changes[1].Content)
	for _, want := range []string{
		"strings.ToUpper(f.UserName())",
		`"strings"`,
		"// Seed returns a factory whose values start from seed.",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("the re-rendered factory does not contain %q:\n%s", want, got)
		}
	}
}

func module(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	write(t, root, "go.mod", "module example.test/project\n\ngo 1.26\n")
	for path, body := range files {
		write(t, root, path, body)
	}
	return root
}

func plan(t *testing.T, root string) []modelbuild.Change {
	t.Helper()
	changes, err := modelbuild.Plan(root)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	return changes
}

func paths(changes []modelbuild.Change) string {
	out := make([]string, 0, len(changes))
	for _, c := range changes {
		out = append(out, c.Path)
	}
	return strings.Join(out, " ")
}

func read(t *testing.T, root, path string) string {
	t.Helper()
	body, err := os.ReadFile(filepath.Join(root, path))
	if err != nil {
		t.Fatal(err)
	}
	return string(body)
}

func write(t *testing.T, root, path, body string) {
	t.Helper()
	full := filepath.Join(root, path)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}
