// Code generated by aru model:build from Ticket.go. DO NOT EDIT.

package models

// Tickets is all that is left of the generated query: the rest was deleted by
// hand, which is what makes the file stale.
func Tickets(db any) *TicketQuery { return &TicketQuery{} }

// TicketQuery is the typed query, emptied.
type TicketQuery struct{}
