package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/evanw/esbuild/pkg/api"
)

const bundleOutput = "assets/bundles_gen.go"
const bundleHeader = "// Code generated by aru view:build (esbuild). DO NOT EDIT.\n"

// buildScripts compiles the two browser entry points into a Go registration.
// The generated file is the manifest and the embedded bytes together: there is
// no runtime file lookup, second hashing scheme, or directory of stale chunks.
// An absent entry is not an error; its previous generated registration is removed.
func buildScripts(root string, stdout io.Writer) error {
	root, err := filepath.Abs(root)
	if err != nil {
		return err
	}
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		return err
	}
	output := filepath.Join(root, bundleOutput)
	old, err := os.ReadFile(output)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	if err == nil && !bytes.HasPrefix(old, []byte(bundleHeader)) {
		return fmt.Errorf("assets: refusing to overwrite %s without its generated header", bundleOutput)
	}
	var entries []api.EntryPoint
	for _, name := range []string{"app", "theme"} {
		input := filepath.Join(root, "resources", "js", name+".js")
		if _, err := os.Stat(input); errors.Is(err, fs.ErrNotExist) {
			continue
		} else if err != nil {
			return err
		}
		entries = append(entries, api.EntryPoint{InputPath: input, OutputPath: name + ".min"})
	}
	if len(entries) == 0 {
		if len(old) != 0 {
			return os.Remove(output)
		}
		return nil
	}
	result := api.Build(api.BuildOptions{
		AbsWorkingDir:       root,
		EntryPointsAdvanced: entries,
		Outdir:              filepath.Join(root, "assets"),
		Bundle:              true, Write: false,
		Platform: api.PlatformBrowser, Format: api.FormatIIFE, Target: api.ES2020,
		MinifyWhitespace: true, MinifyIdentifiers: true, MinifySyntax: true,
		LegalComments:     api.LegalCommentsEndOfFile,
		IgnoreAnnotations: true,
		LogLevel:          api.LogLevelSilent,
		Plugins:           []api.Plugin{localAssetPlugin(root)},
	})
	if len(result.Errors) > 0 {
		return assetMessages(result.Errors)
	}
	// Compiler warnings are actionable build failures. This resolver checks
	// static imports; computed runtime requests still require the site's CSP.
	if len(result.Warnings) > 0 {
		return assetMessages(result.Warnings)
	}
	var source strings.Builder
	source.WriteString(bundleHeader + "\npackage assets\n\nimport \"github.com/arandu-io/hesape/view\"\n\nfunc init() {\n")
	for _, file := range result.OutputFiles {
		if filepath.Ext(file.Path) != ".js" {
			return fmt.Errorf("assets: import styles through resources/css/app.css, not JavaScript")
		}
		fmt.Fprintf(&source, "view.RegisterAsset(%q, %q, []byte(%q))\n", filepath.Base(file.Path), "text/javascript; charset=utf-8", file.Contents)
	}
	source.WriteString("}\n")
	generated, err := format.Source([]byte(source.String()))
	if err != nil {
		return fmt.Errorf("assets: generating registration: %w", err)
	}
	if bytes.Equal(old, generated) {
		return nil
	}
	if err := writeAssetOutput(root, bundleOutput, generated); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "wrote %s (%d JavaScript bundles)\n", bundleOutput, len(result.OutputFiles))
	return nil
}

// localAssetPlugin owns resolution rather than falling back to package.json,
// node_modules, tsconfig path aliases or network URLs. Every file import names
// its extension. Native imports read the consumer's resolved module, not the
// version the CLI itself was compiled with.
func localAssetPlugin(root string) api.Plugin {
	var once sync.Once
	var nativeDir string
	var nativeErr error
	return api.Plugin{Name: "arandu-local-assets", Setup: func(build api.PluginBuild) {
		build.OnResolve(api.OnResolveOptions{Filter: ".*"}, func(args api.OnResolveArgs) (api.OnResolveResult, error) {
			if strings.HasPrefix(args.Path, "arandu:") {
				name := strings.TrimPrefix(args.Path, "arandu:")
				switch name {
				case "htmx.min.js", "ui.js", "basecoat.bundle.js", "theme.js":
				default:
					return api.OnResolveResult{}, fmt.Errorf("unknown native asset %q", args.Path)
				}
				once.Do(func() { nativeDir, nativeErr = nativeAssetsDir(root) })
				if nativeErr != nil {
					return api.OnResolveResult{}, nativeErr
				}
				path, err := confinedAsset(nativeDir, filepath.Join(nativeDir, name))
				return api.OnResolveResult{Path: path, Namespace: "arandu-native"}, err
			}
			path := args.Path
			if args.Kind != api.ResolveEntryPoint {
				if !strings.HasPrefix(path, "./") && !strings.HasPrefix(path, "../") {
					return api.OnResolveResult{}, fmt.Errorf("assets: %q is not a local relative import; npm packages and remote URLs are not supported", path)
				}
				path = filepath.Join(filepath.Dir(args.Importer), path)
			}
			path, err := confinedAsset(root, path)
			if err != nil {
				return api.OnResolveResult{}, err
			}
			if strings.Contains(filepath.ToSlash(path), "/node_modules/") {
				return api.OnResolveResult{}, fmt.Errorf("assets: node_modules imports are not supported")
			}
			return api.OnResolveResult{Path: path, Namespace: "arandu-local"}, nil
		})
		load := func(args api.OnLoadArgs) (api.OnLoadResult, error) {
			var loader api.Loader
			switch filepath.Ext(args.Path) {
			case ".js", ".mjs":
				loader = api.LoaderJS
			case ".ts":
				loader = api.LoaderTS
			case ".json":
				loader = api.LoaderJSON
			default:
				return api.OnLoadResult{}, fmt.Errorf("assets: unsupported import %q; styles belong in resources/css/app.css", args.Path)
			}
			body, err := os.ReadFile(args.Path)
			if err != nil {
				return api.OnLoadResult{}, err
			}
			contents := string(body)
			if args.Namespace == "arandu-native" {
				switch filepath.Base(args.Path) {
				case "htmx.min.js":
					// The vendored browser distribution declares a script global.
					// Modules need to publish that value explicitly after bundling.
					contents += "\nwindow.htmx = htmx;\n"
				case "basecoat.bundle.js":
					// Preserve the upstream notice from the resolved version,
					// including distributions whose leading comment lacks '!'.
					contents = strings.Replace(contents, "/*", "/*!", 1)
				}
			}
			return api.OnLoadResult{Contents: &contents, Loader: loader, ResolveDir: filepath.Dir(args.Path)}, nil
		}
		build.OnLoad(api.OnLoadOptions{Filter: ".*", Namespace: "arandu-local"}, load)
		build.OnLoad(api.OnLoadOptions{Filter: ".*", Namespace: "arandu-native"}, load)
	}}
}

func confinedAsset(root, path string) (string, error) {
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil {
		return "", fmt.Errorf("assets: %w", err)
	}
	rel, err := filepath.Rel(root, resolved)
	if err != nil || !filepath.IsLocal(rel) {
		return "", fmt.Errorf("assets: %q escapes its source root", path)
	}
	return resolved, nil
}

func nativeAssetsDir(root string) (string, error) {
	const module = "github.com/arandu-io/hesape"
	// go list respects go.work, replace and vendoring. No go get, npm registry
	// or CDN lookup happens here; a missing module must be fetched by Go first.
	out, err := goOutput(root, "list", "-f", "{{.Dir}}", module+"/view")
	if err != nil {
		return "", fmt.Errorf("assets: locating native browser assets: %w", err)
	}
	dir, err := filepath.EvalSymlinks(filepath.Join(strings.TrimSpace(out), "assets"))
	if err != nil {
		return "", fmt.Errorf("assets: locating native browser assets: %w", err)
	}
	return dir, nil
}

func assetMessages(messages []api.Message) error {
	var b strings.Builder
	for i, message := range messages {
		if i > 0 {
			b.WriteByte('\n')
		}
		if loc := message.Location; loc != nil {
			fmt.Fprintf(&b, "%s:%d:%d: ", loc.File, loc.Line, loc.Column+1)
		}
		b.WriteString(message.Text)
		for _, note := range message.Notes {
			fmt.Fprintf(&b, "\n  %s", note.Text)
		}
	}
	return fmt.Errorf("assets: %s", b.String())
}

func minifyStylesheet(source []byte) ([]byte, error) {
	result := api.Build(api.BuildOptions{
		Stdin:  &api.StdinOptions{Contents: string(source), Loader: api.LoaderCSS, Sourcefile: stylesheetSource},
		Bundle: true, Write: false, Outfile: "app.css",
		MinifyWhitespace: true, MinifySyntax: true, LegalComments: api.LegalCommentsEndOfFile,
		LogLevel: api.LogLevelSilent,
		Plugins: []api.Plugin{{Name: "arandu-local-css", Setup: func(build api.PluginBuild) {
			build.OnResolve(api.OnResolveOptions{Filter: ".*"}, func(args api.OnResolveArgs) (api.OnResolveResult, error) {
				if args.Kind == api.ResolveCSSURLToken &&
					((strings.HasPrefix(args.Path, "/") && !strings.HasPrefix(args.Path, "//")) || strings.HasPrefix(args.Path, "#") || strings.HasPrefix(args.Path, "data:")) {
					return api.OnResolveResult{Path: args.Path, External: true}, nil
				}
				return api.OnResolveResult{}, fmt.Errorf("assets: CSS reference %q must resolve through Tailwind or a local root-relative asset URL; remote URLs are not supported", args.Path)
			})
		}}},
	})
	if len(result.Errors) > 0 {
		return nil, assetMessages(result.Errors)
	}
	if len(result.Warnings) > 0 {
		return nil, assetMessages(result.Warnings)
	}
	if len(result.OutputFiles) != 1 {
		return nil, fmt.Errorf("assets: expected one compiled stylesheet")
	}
	return result.OutputFiles[0].Contents, nil
}

// writeAssetOutput installs a complete file atomically inside the project.
// os.Root also refuses output-directory symlinks escaping the project.
func writeAssetOutput(root, name string, body []byte) error {
	dir, err := os.OpenRoot(root)
	if err != nil {
		return err
	}
	defer func() { _ = dir.Close() }()
	if err := dir.MkdirAll(filepath.Dir(name), 0o755); err != nil {
		return err
	}
	// The CLI's build loop is serial; O_EXCL prevents a concurrent build from
	// sharing this temporary file rather than silently mixing two outputs.
	temp := name + ".tmp"
	f, err := dir.OpenFile(temp, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return err
	}
	defer func() { _ = dir.Remove(temp) }()
	_, writeErr := f.Write(body)
	closeErr := f.Close()
	if writeErr != nil {
		return writeErr
	}
	if closeErr != nil {
		return closeErr
	}
	return dir.Rename(temp, name)
}
