// Code generated by `aru view:build` from index.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line internal/doctor/testdata/gaps/resources/views/reports/index.kyse.go:5

// ReportsIndexData is the data of this page.
type ReportsIndexData struct {
	Title string
}

//line internal/doctor/testdata/gaps/storage/framework/views/reports/index.go:22

func init() {
	view.Register("internal.doctor.testdata.gaps.resources.views.reports.index", renderInternalDoctorTestdataGapsResourcesViewsReportsIndex)
}

// renderInternalDoctorTestdataGapsResourcesViewsReportsIndex renders internal.doctor.testdata.gaps.resources.views.reports.index.
func renderInternalDoctorTestdataGapsResourcesViewsReportsIndex(w io.Writer, data any) error {
	d, ok := data.(ReportsIndexData)
	if !ok {
		return view.WrongData("internal.doctor.testdata.gaps.resources.views.reports.index", "ReportsIndexData", data)
	}
	_ = d
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<h1>")
	}
	if err == nil {
//line internal/doctor/testdata/gaps/resources/views/reports/index.kyse.go:12
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line internal/doctor/testdata/gaps/storage/framework/views/reports/index.go:45
	}
	if err == nil {
		_, err = io.WriteString(w, "</h1>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<!-- x-on: with double quotes. The audit matched x-data, x-init and x-effect\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "     only, and an event handler is where a network call is actually written. -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div x-on:click=\"fetch('/api/totals')\">Load</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<!-- The shorthand, with single quotes. Same directive, two spellings, and\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "     neither one was matched. -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div @click='fetch(\"/api/totals\")'>Load</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<!-- x-data with single quotes: the directive the audit did match, in the quote\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "     style it did not. -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div x-data='{ socket: new WebSocket(\"/ws\") }'>Live</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<!-- Client-only, and it stays silent: which panel is open dies on reload\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "     without loss, and the server never sees it. -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div x-data=\"{ open: false }\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<button @click=\"open = !open\">Menu</button>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	return err
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
	_ = view.UnsafeText
)
