// Code generated by `aru view:build` from index.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	kyse__template "html/template"
	kyse__io "io"

	kyse__view "github.com/arandu-io/hesape/view"
)

//line internal/doctor/testdata/gaps/resources/views/reports/index.kyse.go:5

// ReportsIndexData is the data of this page.
type ReportsIndexData struct {
	Title string
}

//line internal/doctor/testdata/gaps/storage/framework/views/reports/index.go:22

func init() {
	kyse__view.Register("internal.doctor.testdata.gaps.resources.views.reports.index", renderInternalDoctorTestdataGapsResourcesViewsReportsIndex)
}

// renderInternalDoctorTestdataGapsResourcesViewsReportsIndex renders internal.doctor.testdata.gaps.resources.views.reports.index.
func renderInternalDoctorTestdataGapsResourcesViewsReportsIndex(kyse__w kyse__io.Writer, kyse__data any) error {
	kyse__d, kyse__ok := kyse__data.(ReportsIndexData)
	if !kyse__ok {
		return kyse__view.WrongData("internal.doctor.testdata.gaps.resources.views.reports.index", "ReportsIndexData", kyse__data)
	}
	_ = kyse__d
	d := kyse__d
	_ = d
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<h1>")
	}
	if kyse__err == nil {
//line internal/doctor/testdata/gaps/resources/views/reports/index.kyse.go:12
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Title)))
//line internal/doctor/testdata/gaps/storage/framework/views/reports/index.go:47
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</h1>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<!-- x-on: with double quotes. The audit matched x-data, x-init and x-effect\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     only, and an event handler is where a network call is actually written. -->\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div x-on:click=\"fetch('/api/totals')\">Load</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<!-- The shorthand, with single quotes. Same directive, two spellings, and\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     neither one was matched. -->\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div @click='fetch(\"/api/totals\")'>Load</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<!-- x-data with single quotes: the directive the audit did match, in the quote\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     style it did not. -->\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div x-data='{ socket: new WebSocket(\"/ws\") }'>Live</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<!-- Client-only, and reported all the same: which panel is open dies on reload\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     without loss, and the server never sees it -- but nothing this stack serves\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     evaluates the directive, so the menu does not open and no error says so.\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     This block is the widening, and the one below is where it stops. -->\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div x-data=\"{ open: false }\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<button @click=\"open = !open\">Menu</button>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<!-- The same menu, spelled the way the behaviours file reads it, and silent.\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     A rule that fired here would be a rule teaching people to mute it: hx- is\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     not the family, data- is not the family, and neither is an attribute that\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     merely ends in one of the names. -->\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div data-menu>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<button data-menu-trigger aria-expanded=\"false\" hx-get=\"/reports/menu\">Menu</button>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<div data-x-id=\"not-a-directive\" class=\"combobox-initialized\"></div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	return kyse__err
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
)
