package fonts

import (
	"fmt"
	"sort"
	"strings"
)

// Role is what a face is used for. There are two, and that is the whole set.
//
// Display is headings and the masthead; body is running text. A third would be
// a third file in every binary and a third decision on every page, and the
// answer to "what about captions" is a weight, not a family.
type Role string

// The two roles.
const (
	Display Role = "display"
	Body    Role = "body"
)

// Roles is the closed set, in the order they are written.
var Roles = []Role{Display, Body}

// Valid reports whether a role is one of the two.
func (r Role) Valid() bool {
	return r == Display || r == Body
}

// Installed is one vendored family and what it is used for.
type Installed struct {
	Role     Role
	Family   string
	Weight   string
	Subsets  []string
	Category string
	License  string
	Metrics  Metrics
	FileList []string
}

// Stylesheet renders the @font-face rules and the two custom properties the
// design tokens read.
//
// It is generated rather than hand-written for the two things a person gets
// wrong: the unicode-range, which has to match what the file actually covers,
// and the metric overrides, which are three numbers nobody can guess.
//
// # Why the fallback face exists
//
// `font-display: swap` guarantees a reflow: the page paints in the system font
// and then every line moves when the real one arrives. The fix is a second
// @font-face over a LOCAL font, stretched so it occupies the same space -- same
// ascent, same descent, same x-height. The swap then changes the shapes without
// moving anything, which is the difference between a font that is free and a
// font that costs a layout shift on every first visit.
func Stylesheet(installed []Installed) string {
	var b strings.Builder

	b.WriteString(`/* Generated by ` + "`aru font:add`" + `. Do not edit -- the command rewrites it.
 *
 * The files are vendored under assets/fonts/ and committed, so nothing is
 * fetched at build time and nothing at all at run time. The CSP is
 * default-src 'self' (font-src 'self' is spelled out beside it), and a font
 * from a CDN would mean loosening it in order to look different.
 *
 * The url() carries the FONT's own content hash, not the stylesheet's.
 *
 * A relative url() would resolve against /_arandu/assets/<cssHash>/ and reach
 * the file -- but the framework compares the hash in the path against the hash
 * of the bytes, and serves a mismatch with Cache-Control: no-cache. On purpose:
 * a stale reference degrades into a slow page rather than a broken one. So a
 * relative url() means the font is re-downloaded on EVERY page view, silently,
 * with nothing broken enough to notice.
 *
 * The hash below is view.AssetHash, computed here. That is a contract across a
 * repository boundary, and both sides carry a test that pins it.
 */

`)

	sorted := append([]Installed(nil), installed...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Role < sorted[j].Role })

	for _, in := range sorted {
		fmt.Fprintf(&b, "/* %s: %s", in.Role, in.Family)
		if in.License != "" {
			fmt.Fprintf(&b, ", %s", strings.ToUpper(in.License))
		}
		fmt.Fprintf(&b, " */\n")

		for _, face := range in.FileList {
			file, unicodeRange, hash := parseFileNote(face)

			fmt.Fprintf(&b, `@font-face {
  font-family: %q;
  font-style: normal;
  font-weight: %s;
  font-display: swap;
  src: url("%s") format(%q);
`, in.Family, cssWeight(in.Weight), assetURL(hash, file), Format(file))
			if unicodeRange != "" {
				fmt.Fprintf(&b, "  unicode-range: %s;\n", unicodeRange)
			}
			b.WriteString("}\n")
		}

		// The metric-matched fallback. Skipped when the metrics could not be
		// read: a made-up override is worse than none, because it shifts the
		// layout in a direction nobody measured.
		if in.Metrics.Ascent > 0 {
			fmt.Fprintf(&b, `
/* The fallback, stretched to occupy exactly the space %s will.
 * Without it, swap reflows every line under the heading when the font lands. */
@font-face {
  font-family: %q;
  src: %s;
  ascent-override: %.2f%%;
  descent-override: %.2f%%;
  line-gap-override: %.2f%%;
`, in.Family, string(in.Role)+"-fallback", localFaces(in.Category),
				in.Metrics.Ascent, in.Metrics.Descent, in.Metrics.LineGap)
			if in.Metrics.SizeAdjust > 0 {
				fmt.Fprintf(&b, "  size-adjust: %.2f%%;\n", in.Metrics.SizeAdjust)
			}
			b.WriteString("}\n")
		}
		b.WriteString("\n")
	}

	// The two properties the rest of the stylesheet reads. A view never names a
	// family: it names --font-display or --font-sans, and swapping the face is
	// this file changing rather than every template.
	b.WriteString("@theme {\n")
	for _, in := range sorted {
		token := "--font-display"
		if in.Role == Body {
			token = "--font-sans"
		}
		fallback := string(in.Role) + "-fallback"
		if in.Metrics.Ascent == 0 {
			fallback = ""
		}

		stack := []string{fmt.Sprintf("%q", in.Family)}
		if fallback != "" {
			stack = append(stack, fmt.Sprintf("%q", fallback))
		}
		stack = append(stack, systemStack(in.Category))
		fmt.Fprintf(&b, "  %s: %s;\n", token, strings.Join(stack, ", "))
	}
	b.WriteString("}\n")

	return b.String()
}

// systemStack is what is drawn before the font arrives, and after it fails.
//
// It follows the CATEGORY and not the role. Following the role assumes a display
// face is a serif, so installing Montserrat as the display face produces a page
// that paints in Georgia and becomes a geometric sans. The metric override
// cannot hide that: it matches the space, not the drawing.
func systemStack(category string) string {
	switch kind(category) {
	case "serif":
		return `Georgia, "Times New Roman", serif`
	case "monospace":
		return `ui-monospace, "SF Mono", Menlo, monospace`
	default:
		return `ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif`
	}
}

// localFaces is what the metric-matched fallback is drawn from.
//
// local() and not a generic family, because the overrides stretch a SPECIFIC
// face: ascent, descent and x-height are properties of one drawing, and
// "sans-serif" is whatever the machine decided that means.
//
// The list is ordered by what is actually installed. Every one of these ships
// with either macOS or Windows, and the first match wins.
func localFaces(category string) string {
	switch kind(category) {
	case "serif":
		return `local("Georgia"), local("Times New Roman"), local("Times")`
	case "monospace":
		return `local("SF Mono"), local("Menlo"), local("Consolas")`
	default:
		return `local("Helvetica Neue"), local("Arial"), local("Segoe UI"), local("Roboto")`
	}
}

// kind reduces the source's classification to what the fallback turns on.
//
// Display and Handwriting are neither serif nor mono in any useful sense --
// what they have in common with a sans is that a sans is the least wrong thing
// to paint before they arrive.
func kind(category string) string {
	switch compact(category) {
	case "serif":
		return "serif"
	case "monospace":
		return "monospace"
	default:
		return "sans"
	}
}

// cssWeight turns the API's spelling into the property's.
//
// "400..700" is a range in a URL and "400 700" is a range in CSS, and a variable
// font declared at a single weight is a variable font locked to one instance.
func cssWeight(w string) string {
	if w == "" {
		return "400"
	}
	w = strings.ReplaceAll(w, "..", " ")
	return strings.ReplaceAll(w, ";", " ")
}

// parseFileNote splits the "file|unicode-range|hash" the caller packs.
//
// Three fields in a string rather than a struct because the manifest has to
// round-trip through a line of TOML, and a struct would need a second
// representation to get there.
func parseFileNote(note string) (file, unicodeRange, hash string) {
	file, rest, _ := strings.Cut(note, "|")
	unicodeRange, hash, _ = strings.Cut(rest, "|")
	return file, unicodeRange, hash
}

// Format is what the src: declares, from the extension.
//
// It is not decoration: a browser skips a source whose format it does not
// support without downloading it, so a .ttf declared as woff2 is a font every
// browser fetches and then refuses -- with an error naming neither the file nor
// the declaration.
func Format(file string) string {
	switch {
	case strings.HasSuffix(file, ".ttf"):
		return "truetype"
	case strings.HasSuffix(file, ".otf"):
		return "opentype"
	default:
		return "woff2"
	}
}

// ContentType is what the framework serves a vendored face as.
func ContentType(file string) string {
	switch {
	case strings.HasSuffix(file, ".ttf"):
		return "font/ttf"
	case strings.HasSuffix(file, ".otf"):
		return "font/otf"
	default:
		return "font/woff2"
	}
}

// assetURL is where the framework serves a file with that content hash.
//
// The path shape is view.AssetPath + hash + "/" + name, and it is spelled out
// here because the CLI cannot import the framework. A hash the caller could not
// compute leaves the URL relative, which still reaches the file -- slowly.
func assetURL(hash, file string) string {
	if hash == "" {
		return file
	}
	return "/_arandu/assets/" + hash + "/" + file
}
