// Code generated by `aru view:build` from index.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	kyse__template "html/template"
	kyse__io "io"

	kyse__view "github.com/arandu-io/hesape/view"
)

//line internal/doctor/testdata/violations/resources/views/billing/index.kyse.go:5

// BillingIndexData is the data of this page.
type BillingIndexData struct {
	Title string
	Note  string
}

//line internal/doctor/testdata/violations/storage/framework/views/billing/index.go:23

func init() {
	kyse__view.Register("internal.doctor.testdata.violations.resources.views.billing.index", renderInternalDoctorTestdataViolationsResourcesViewsBillingIndex)
}

// renderInternalDoctorTestdataViolationsResourcesViewsBillingIndex renders internal.doctor.testdata.violations.resources.views.billing.index.
func renderInternalDoctorTestdataViolationsResourcesViewsBillingIndex(kyse__w kyse__io.Writer, kyse__data any) error {
	kyse__d, kyse__ok := kyse__data.(BillingIndexData)
	if !kyse__ok {
		return kyse__view.WrongData("internal.doctor.testdata.violations.resources.views.billing.index", "BillingIndexData", kyse__data)
	}
	_ = kyse__d
	d := kyse__d
	_ = d
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<h1>")
	}
	if kyse__err == nil {
//line internal/doctor/testdata/violations/resources/views/billing/index.kyse.go:13
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Title)))
//line internal/doctor/testdata/violations/storage/framework/views/billing/index.go:48
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</h1>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<!-- Violation: the raw form writes a value to the page with no escaping. Note\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     is a string, it is rendered as markup, and the day it holds something a\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     customer typed the page runs it. The escaped form is three characters\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     away. -->\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div class=\"note\">")
	}
	if kyse__err == nil {
//line internal/doctor/testdata/violations/resources/views/billing/index.kyse.go:19
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.Text(kyse__d.Note))
//line internal/doctor/testdata/violations/storage/framework/views/billing/index.go:74
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<!-- Violation, and the expensive kind: a directive that fetches. This should be\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     an HTMX fragment -- the moment it loads data of its own, the application has\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     two ways to do it, with two loading states and two places to forget the CSRF\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     token. -->\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div x-data=\"{ open: false, invoices: [], async load() { const r = await fetch('/api/invoices'); this.invoices = await r.json() } }\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<button @click=\"open = !open\">Toggle</button>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<!-- Violation, and the ordinary kind: open/closed never leaves the page, and\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     the directive is still a finding because nothing here evaluates one. The\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     screen does nothing and says nothing about why. The behaviours file the\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "     layout loads owns this, on a data- attribute. -->\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<div x-data=\"{ open: false }\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<button @click=\"open = !open\">Menu</button>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</div>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	return kyse__err
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
)
