// Code generated by `aru view:build` from index.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line internal/doctor/testdata/clean/resources/views/invoices/index.kyse.go:5

// InvoicesIndexData is the data of this page, and only of this page.
type InvoicesIndexData struct {
	Title    string
	Invoices []models.Invoice
}

//line internal/doctor/testdata/clean/resources/views/invoices/index.go:23

func init() {
	view.Register("internal.doctor.testdata.clean.resources.views.invoices.index", renderInternalDoctorTestdataCleanResourcesViewsInvoicesIndex)
}

// renderInternalDoctorTestdataCleanResourcesViewsInvoicesIndex renders internal.doctor.testdata.clean.resources.views.invoices.index.
func renderInternalDoctorTestdataCleanResourcesViewsInvoicesIndex(w io.Writer, data any) error {
	d, ok := data.(InvoicesIndexData)
	if !ok {
		return view.WrongData("internal.doctor.testdata.clean.resources.views.invoices.index", "InvoicesIndexData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<h1 class=\"text-2xl font-semibold\">")
			}
			if err == nil {
//line internal/doctor/testdata/clean/resources/views/invoices/index.kyse.go:16
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line internal/doctor/testdata/clean/resources/views/invoices/index.go:45
			}
			if err == nil {
				_, err = io.WriteString(w, "</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<!-- Alpine within its limit: which tab is open is client state, it dies on\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t     reload without loss, and the server never sees it. -->\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<div x-data=\"{ tab: 0 }\" class=\"mt-4 flex gap-2\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<button @click=\"tab = 0\" class=\"rounded px-3 py-1\">All</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\t<button @click=\"tab = 1\" class=\"rounded px-3 py-1\">Overdue</button>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</div>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<ul class=\"mt-4 divide-y\">\n")
			}
//line internal/doctor/testdata/clean/resources/views/invoices/index.kyse.go:26
			for _, invoice := range d.Invoices {
				_ = invoice
//line internal/doctor/testdata/clean/resources/views/invoices/index.go:80
				if err == nil {
					_, err = io.WriteString(w, "\t\t\t<li class=\"py-2\">")
				}
				if err == nil {
//line internal/doctor/testdata/clean/resources/views/invoices/index.kyse.go:27
					_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(invoice.Reference)))
//line internal/doctor/testdata/clean/resources/views/invoices/index.go:87
				}
				if err == nil {
					_, err = io.WriteString(w, "</li>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</ul>\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
