// Code generated by `aru view:build` from row.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line internal/doctor/testdata/clean/resources/views/invoices/row.kyse.go:5

// InvoiceRowData is one row, rendered as an HTMX fragment.
type InvoiceRowData struct {
	Invoice models.Invoice
}

//line internal/doctor/testdata/clean/resources/views/invoices/row.go:22

func init() {
	view.Register("internal.doctor.testdata.clean.resources.views.invoices.row", renderInternalDoctorTestdataCleanResourcesViewsInvoicesRow)
}

// renderInternalDoctorTestdataCleanResourcesViewsInvoicesRow renders internal.doctor.testdata.clean.resources.views.invoices.row.
func renderInternalDoctorTestdataCleanResourcesViewsInvoicesRow(w io.Writer, data any) error {
	d, ok := data.(InvoiceRowData)
	if !ok {
		return view.WrongData("internal.doctor.testdata.clean.resources.views.invoices.row", "InvoiceRowData", data)
	}
	_ = d
	var err error
	if err == nil {
		_, err = io.WriteString(w, "<li class=\"py-2\" id=\"invoice-")
	}
	if err == nil {
//line internal/doctor/testdata/clean/resources/views/invoices/row.kyse.go:12
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Invoice.ID)))
//line internal/doctor/testdata/clean/resources/views/invoices/row.go:42
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<span class=\"font-medium\">")
	}
	if err == nil {
//line internal/doctor/testdata/clean/resources/views/invoices/row.kyse.go:13
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Invoice.Reference)))
//line internal/doctor/testdata/clean/resources/views/invoices/row.go:53
	}
	if err == nil {
		_, err = io.WriteString(w, "</span>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<span class=\"text-slate-500\">")
	}
	if err == nil {
//line internal/doctor/testdata/clean/resources/views/invoices/row.kyse.go:14
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Invoice.Total)))
//line internal/doctor/testdata/clean/resources/views/invoices/row.go:64
	}
	if err == nil {
		_, err = io.WriteString(w, "</span>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</li>\n")
	}
	return err
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
