// Code generated by `aru view:build` from app.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	kyse__template "html/template"
	kyse__io "io"

	kyse__view "github.com/arandu-io/framework/view"
)

//line internal/doctor/testdata/clean/resources/views/layouts/app.kyse.go:5

// LayoutData is what every page hands the layout.
type LayoutData struct {
	Title string
}

//line internal/doctor/testdata/clean/storage/framework/views/layouts/app.go:22

func init() {
	kyse__view.RegisterLayout("internal.doctor.testdata.clean.resources.views.layouts.app", renderInternalDoctorTestdataCleanResourcesViewsLayoutsApp)
}

// renderInternalDoctorTestdataCleanResourcesViewsLayoutsApp renders the internal.doctor.testdata.clean.resources.views.layouts.app layout.
func renderInternalDoctorTestdataCleanResourcesViewsLayoutsApp(kyse__w kyse__io.Writer, kyse__data any, kyse__sections map[string]func(kyse__io.Writer) error) error {
	kyse__d, kyse__ok := kyse__data.(kyse__view.Layout)
	if !kyse__ok {
		return kyse__view.WrongData("internal.doctor.testdata.clean.resources.views.layouts.app", "view.Layout", kyse__data)
	}
	_ = kyse__d
	d := kyse__d
	_ = d
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<!doctype html>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<html lang=\"en\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<head>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<meta charset=\"utf-8\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<title>")
	}
	if kyse__err == nil {
//line internal/doctor/testdata/clean/resources/views/layouts/app.kyse.go:16
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Title)))
//line internal/doctor/testdata/clean/storage/framework/views/layouts/app.go:59
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</title>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<link rel=\"stylesheet\" href=\"/assets/app.css\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</head>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<body class=\"bg-white text-slate-900\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<main class=\"mx-auto max-w-3xl p-6\">\n")
	}
	if kyse__err == nil {
		kyse__err = kyse__view.Yield(kyse__w, kyse__sections, "content")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t</main>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</body>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</html>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	return kyse__err
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__view.UnsafeText
)
