// Code generated by `aru view:build` from app.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line internal/doctor/testdata/clean/resources/views/layouts/app.kyse.go:5

// LayoutData is what every page hands the layout.
type LayoutData struct {
	Title string
}

//line internal/doctor/testdata/clean/storage/framework/views/layouts/app.go:22

func init() {
	view.RegisterLayout("internal.doctor.testdata.clean.resources.views.layouts.app", renderInternalDoctorTestdataCleanResourcesViewsLayoutsApp)
}

// renderInternalDoctorTestdataCleanResourcesViewsLayoutsApp renders the internal.doctor.testdata.clean.resources.views.layouts.app layout.
func renderInternalDoctorTestdataCleanResourcesViewsLayoutsApp(w io.Writer, data any, sections map[string]func(io.Writer) error) error {
	d, ok := data.(view.Layout)
	if !ok {
		return view.WrongData("internal.doctor.testdata.clean.resources.views.layouts.app", "view.Layout", data)
	}
	_ = d
	var err error
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<!doctype html>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<html lang=\"en\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta charset=\"utf-8\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<title>")
	}
	if err == nil {
//line internal/doctor/testdata/clean/resources/views/layouts/app.kyse.go:16
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line internal/doctor/testdata/clean/storage/framework/views/layouts/app.go:57
	}
	if err == nil {
		_, err = io.WriteString(w, "</title>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<link rel=\"stylesheet\" href=\"/assets/app.css\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<body class=\"bg-white text-slate-900\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<main class=\"mx-auto max-w-3xl p-6\">\n")
	}
	if err == nil {
		err = view.Yield(w, sections, "content")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t</main>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</body>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</html>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\n")
	}
	return err
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
