package kyse

import (
	"fmt"
	"go/format"
	"path"
	"strconv"
	"strings"
)

// Generate turns a parsed view into the Go that renders it.
//
// The output is a function that writes strings to an io.Writer, plus an init()
// that registers it under the view's name. No runtime parse, no cache
// directory, no reflection: the data is the struct the view declared in its
// `@go` block, and a field that does not exist stops the build.
//
// Laravel compiles Blade to PHP at runtime and caches it in
// storage/framework/views. Same idea, moved to build time -- which is what makes
// the typo a compile error instead of a warning nobody reads in production.
func Generate(f *File, name, dataType string) ([]byte, error) {
	// A view that reads a field with no type to read it from cannot produce Go
	// that compiles, and it has to be said here rather than by the Go compiler
	// three steps later. See dataReference.
	if dataType == "" {
		if expr, line, found := dataReference(f); found {
			return nil, &Error{
				Path:    f.Path,
				Line:    line,
				Message: fmt.Sprintf("%s reads a field of the page data, and this view declares no type for it", expr),
				Hint: "declare the struct inside @go … @endgo, which is the only place Go is Go:\n" +
					"        @go\n" +
					"        type PageData struct{ … }\n" +
					"        @endgo\n" +
					"    A type declaration outside the block is markup, not a declaration.\n" +
					"    A view that extends a layout inherits the layout's type instead.",
			}
		}
	}

	g := &generator{file: f, name: name, dataType: dataType}
	g.emit()

	src := g.out.String()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		// The generated Go not parsing is a bug in this generator, never in the
		// view. Saying so saves the reader from looking in the wrong file.
		return nil, fmt.Errorf("kyse: the Go generated from %s does not parse -- this is a bug in the generator: %w\n%s",
			f.Path, err, numbered(src))
	}
	return formatted, nil
}

type generator struct {
	file     *File
	name     string
	dataType string
	out      strings.Builder
	// fn is the current writer variable, so nested helpers write to the same place.
	depth int
}

func (g *generator) emit() {
	fmt.Fprintf(&g.out, "// Code generated by `aru view:build` from %s. DO NOT EDIT.\n",
		path.Base(g.file.Path))
	fmt.Fprintf(&g.out, "//\n// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.\n\n")
	fmt.Fprintf(&g.out, "package %s\n\n", g.file.Package)

	g.out.WriteString("import (\n")
	g.out.WriteString("\t\"html/template\"\n\t\"io\"\n\n")
	g.out.WriteString("\t\"github.com/arandu-io/framework/view\"\n")
	g.out.WriteString(")\n\n")

	// The @go blocks, verbatim. This is where the data struct is declared.
	for _, block := range g.file.Go {
		g.out.WriteString(block)
		g.out.WriteString("\n")
	}

	fn := funcName(g.name)
	isLayout := g.yields()

	// A layout is handed the sections the child view declared; a page is not.
	// Two different contracts, and so two registries -- the @yield in the source
	// is what decides which one this file is.
	if isLayout {
		fmt.Fprintf(&g.out, "func init() { view.RegisterLayout(%s, %s) }\n\n", strconv.Quote(g.name), fn)
		fmt.Fprintf(&g.out, "// %s renders the %s layout.\nfunc %s(w io.Writer, data any, sections map[string]func(io.Writer) error) error {\n", fn, g.name, fn)
	} else {
		fmt.Fprintf(&g.out, "func init() { view.Register(%s, %s) }\n\n", strconv.Quote(g.name), fn)
		fmt.Fprintf(&g.out, "// %s renders %s.\nfunc %s(w io.Writer, data any) error {\n", fn, g.name, fn)
	}

	if g.dataType != "" {
		fmt.Fprintf(&g.out, "\td, ok := data.(%s)\n", g.dataType)
		fmt.Fprintf(&g.out, "\tif !ok {\n\t\treturn view.WrongData(%s, %s, data)\n\t}\n",
			strconv.Quote(g.name), strconv.Quote(g.dataType))
		// `d` may go unused: a layout that is only @yield interpolates nothing.
		g.out.WriteString("\t_ = d\n")
	} else {
		g.out.WriteString("\t_ = data\n")
	}
	switch {
	case g.file.Extends != "":
		// A view that extends a layout renders the layout, handing it the
		// sections as a map the @yield reads. The layout is a view like any
		// other, so this is one render calling another.
		g.emitSections()
		fmt.Fprintf(&g.out, "\treturn view.RenderInto(w, %s, data, sections)\n", strconv.Quote(g.file.Extends))
	default:
		g.out.WriteString("\tvar err error\n")
		for _, n := range g.file.Body {
			g.node(n)
		}
		g.out.WriteString("\treturn err\n")
	}

	g.out.WriteString("}\n")
	g.silenceUnused()
}

// emitSections builds the map a layout's @yield reads.
func (g *generator) emitSections() {
	g.out.WriteString("\tsections := map[string]func(io.Writer) error{\n")
	for _, s := range g.file.Sections {
		fmt.Fprintf(&g.out, "\t\t%s: func(w io.Writer) error {\n\t\t\tvar err error\n", strconv.Quote(s.Name))
		for _, n := range s.Nodes {
			g.node(n)
		}
		g.out.WriteString("\t\t\treturn err\n\t\t},\n")
	}
	g.out.WriteString("\t}\n")
}

func (g *generator) node(n Node) {
	switch n.Kind {
	case Text:
		if n.Body == "" {
			return
		}
		fmt.Fprintf(&g.out, "\tif err == nil { _, err = io.WriteString(w, %s) }\n", strconv.Quote(n.Body))

	case Echo:
		// template.HTMLEscapeString is the same escape Blade's e() does, and it
		// is not optional: a view that interpolates without escaping is the XSS
		// this framework refuses to make easy.
		fmt.Fprintf(&g.out, "\tif err == nil { _, err = io.WriteString(w, template.HTMLEscapeString(view.Text(%s))) }\n",
			g.expr(n.Body))

	case Raw:
		fmt.Fprintf(&g.out, "\tif err == nil { _, err = io.WriteString(w, view.Text(%s)) }\n", g.expr(n.Body))

	case Directive:
		g.directive(n)
	}
}

func (g *generator) directive(n Node) {
	switch n.Name {
	case "if":
		fmt.Fprintf(&g.out, "\tif %s {\n", g.cond(n.Body))
		// @else and @elseif arrive as children, because they are inline
		// directives inside the block the parser opened. Each one closes the
		// branch in progress and opens the next.
		//
		// Without this they had no case at all and were dropped in silence:
		// @if(x) A @else B @endif emitted `if x { A; B }`, so both halves
		// appeared when the condition held and neither when it did not.
		for _, c := range n.Children {
			if c.Kind == Directive && (c.Name == "else" || c.Name == "elseif") {
				if c.Name == "else" {
					g.out.WriteString("\t} else {\n")
				} else {
					fmt.Fprintf(&g.out, "\t} else if %s {\n", g.cond(c.Body))
				}
				continue
			}
			g.node(c)
		}
		g.out.WriteString("\t}\n")

	case "else", "elseif":
		// Reached only outside an @if, where the branch above never sees it.
		// Emitting nothing is what hid the bug for as long as it lived, so this
		// writes Go that does not compile, naming the file and the fix.
		fmt.Fprintf(&g.out, "\t#error @%s outside @if in %s: every @%s needs an @if above it and an @endif below\n",
			n.Name, path.Base(g.file.Path), n.Name)

	case "foreach":
		// @foreach(.Items as item) -> for _, item := range d.Items
		subject, binding := splitAs(n.Body)
		if binding == "" {
			binding = "item"
		}
		fmt.Fprintf(&g.out, "\tfor _, %s := range %s {\n\t\t_ = %s\n", binding, g.expr(subject), binding)
		for _, c := range n.Children {
			g.node(c)
		}
		g.out.WriteString("\t}\n")

	case "yield":
		// Only meaningful inside a layout: it renders the section the child view
		// declared, or nothing when it declared none.
		fmt.Fprintf(&g.out, "\tif err == nil { err = view.Yield(w, sections, %s) }\n",
			strconv.Quote(unquote(n.Body)))

	case "include":
		fmt.Fprintf(&g.out, "\tif err == nil { err = view.Include(w, %s, data) }\n",
			strconv.Quote(unquote(n.Body)))

	case "csrf":
		g.out.WriteString("\tif err == nil { err = view.CSRF(w, data) }\n")
	}
}

// dataReference finds the first expression that reads a field of the page data.
//
// `{{ .Name }}` compiles to `d.Name`, and `d` is declared only when the view has
// a data type -- from its own `@go` block, or inherited from the layout it
// extends. Without one the generator emitted `_ = data` and then `d.Name`, which
// parses; so `format.Source` accepted it, the command reported success, and the
// failure arrived later as `undefined: d` in a file whose header says DO NOT
// EDIT. Naming the `.kyse.go` and the line is the whole reason this compiler
// exists rather than a template library.
func dataReference(f *File) (expr string, line int, found bool) {
	var walk func([]Node) bool
	walk = func(nodes []Node) bool {
		for _, n := range nodes {
			for _, e := range goExpressions(n) {
				if e = strings.TrimSpace(e); strings.HasPrefix(e, ".") {
					expr, line, found = e, n.Line, true
					return true
				}
			}
			if walk(n.Children) {
				return true
			}
		}
		return false
	}

	if walk(f.Body) {
		return expr, line, true
	}
	// A view that extends a layout keeps everything in sections and leaves its
	// body empty, so stopping at the body would miss every page written the
	// ordinary way.
	for _, s := range f.Sections {
		if walk(s.Nodes) {
			return expr, line, true
		}
	}
	return "", 0, false
}

// goExpressions are the parts of a node that reach expr and become Go.
func goExpressions(n Node) []string {
	switch n.Kind {
	case Echo, Raw:
		return []string{n.Body}
	case Directive:
		switch n.Name {
		case "if", "elseif":
			return []string{n.Body}
		case "foreach":
			subject, _ := splitAs(n.Body)
			return []string{subject}
		}
	}
	return nil
}

// expr turns a view expression into a Go one.
//
// `.Name` means "a field of the data", which is what a Blade `$name` means in
// context. Everything else is passed through, so `len(d.Items)` and a helper
// call work -- the view is Go, and pretending otherwise would be inventing a
// second expression language (RULE 15).
func (g *generator) expr(e string) string {
	e = strings.TrimSpace(e)
	if strings.HasPrefix(e, ".") {
		return "d" + e
	}
	return e
}

// cond is expr for a boolean position, where a bare field is the condition.
func (g *generator) cond(e string) string { return g.expr(e) }

// splitAs reads `.Items as item`.
func splitAs(s string) (subject, binding string) {
	parts := strings.SplitN(s, " as ", 2)
	if len(parts) == 2 {
		return strings.TrimSpace(parts[0]), strings.TrimSpace(parts[1])
	}
	return strings.TrimSpace(s), ""
}

// silenceUnused keeps the generated file compiling when a view uses none of the
// imports -- a layout with no interpolation, for instance.
func (g *generator) silenceUnused() {
	g.out.WriteString("\nvar (\n")
	g.out.WriteString("\t_ = template.HTMLEscapeString\n")
	g.out.WriteString("\t_ = io.WriteString\n")
	g.out.WriteString(")\n")
}

// funcName turns "auth/login" into "renderAuthLogin".
func funcName(name string) string {
	var b strings.Builder
	b.WriteString("render")
	for _, part := range strings.FieldsFunc(name, func(r rune) bool {
		return r == '/' || r == '-' || r == '_' || r == '.'
	}) {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}

func numbered(src string) string {
	var b strings.Builder
	for i, line := range strings.Split(src, "\n") {
		fmt.Fprintf(&b, "%4d| %s\n", i+1, line)
	}
	return b.String()
}

// yields reports whether the view has a @yield, which is what makes it a layout.
//
// The distinction is not a naming convention: a layout receives the sections a
// child declared, and a page does not. The source says which by containing the
// directive that reads them.
func (g *generator) yields() bool {
	var walk func([]Node) bool
	walk = func(nodes []Node) bool {
		for _, n := range nodes {
			if n.Kind == Directive && n.Name == "yield" {
				return true
			}
			if walk(n.Children) {
				return true
			}
		}
		return false
	}
	return walk(g.file.Body)
}
