package lsp_test

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/arandu-io/aru/internal/lsp"
)

// The component fixture, in the two files a kyse component is written as.
//
// The generated `.go` is the file the compiler reads and the file a naive
// answer would open; the `.kyse.go` beside it is the one a person edits. The
// pair is the whole point of the test: an editor that lands on the generated
// file shows a header saying not to change it.
const (
	buttonSource = `//go:build kyse

package components

@go
// ButtonProps is what a button is drawn from.
type ButtonProps struct {
	Label string
}
@endgo

<button class="btn">{{ .Label }}</button>
`

	buttonGenerated = `// Code generated by ` + "`aru view:build`" + ` from button.kyse.go. DO NOT EDIT.

package components

import kyse__template "html/template"

type ButtonProps struct {
	Label string
}

// Button draws a button.
func Button(kyse__props ButtonProps) kyse__template.HTML {
	return kyse__template.HTML("<button>" + kyse__props.Label + "</button>")
}
`

	layoutSource = `//go:build kyse

package layouts

<html><body>@yield('content')</body></html>
`
)

// homeView is the view every definition test asks from. It imports the
// component package and calls into it exactly the way the skeleton's layout
// does, so the positions below are positions in real markup.
const homeView = `//go:build kyse

package views

import "example.test/app/resources/views/components"

@extends('layouts.app')

@section('content')
	<p>components.Button is written here as prose, not as a call.</p>
	{!! components.Button(components.ButtonProps{Label: "Save"}) !!}
@endsection
`

func writeDefinitionFixture(t *testing.T, root string) {
	t.Helper()
	files := map[string]string{
		"go.mod": `module example.test/app

go 1.26
`,
		"resources/views/home.kyse.go":              homeView,
		"resources/views/layouts/app.kyse.go":       layoutSource,
		"resources/views/components/button.kyse.go": buttonSource,
		"resources/views/components/button.go":      buttonGenerated,
	}
	for name, contents := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("create fixture directory: %v", err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			t.Fatalf("write fixture %s: %v", name, err)
		}
	}
}

type protocolLocation struct {
	URI   string `json:"uri"`
	Range struct {
		Start struct {
			Line      int `json:"line"`
			Character int `json:"character"`
		} `json:"start"`
	} `json:"range"`
}

// definitionAt drives one go-to-definition over the protocol.
//
// The document is opened with the given text so the request is answered from
// the buffer, which is where an editor's copy lives -- a person navigating from
// an edit they have not saved must not be sent to the file as it was on disk.
func definitionAt(t *testing.T, root, text string, line, character int) []protocolLocation {
	t.Helper()
	rootURI := (&url.URL{Scheme: "file", Path: root}).String()
	input := frames(
		fmt.Sprintf(`{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"rootUri":%q}}`, rootURI),
		fmt.Sprintf(`{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///doc/home.kyse.go","languageId":"kyse","version":1,"text":%q}}}`, text),
		fmt.Sprintf(`{"jsonrpc":"2.0","id":"definition","method":"textDocument/definition","params":{"textDocument":{"uri":"file:///doc/home.kyse.go"},"position":{"line":%d,"character":%d}}}`, line, character),
		`{"jsonrpc":"2.0","id":2,"method":"shutdown"}`,
		`{"jsonrpc":"2.0","method":"exit"}`,
	)
	var output bytes.Buffer
	if err := lsp.Serve(bytes.NewReader(input), &output); err != nil {
		t.Fatalf("serve: %v", err)
	}
	for _, body := range readFrames(t, output.Bytes()) {
		var message struct {
			ID     json.RawMessage `json:"id"`
			Result json.RawMessage `json:"result"`
			Error  *struct {
				Code    int    `json:"code"`
				Message string `json:"message"`
			} `json:"error"`
		}
		if err := json.Unmarshal(body, &message); err != nil {
			t.Fatalf("decode response: %v", err)
		}
		if string(message.ID) != `"definition"` {
			continue
		}
		if message.Error != nil {
			t.Fatalf("definition answered error %d: %s", message.Error.Code, message.Error.Message)
		}
		var locations []protocolLocation
		if err := json.Unmarshal(message.Result, &locations); err != nil {
			t.Fatalf("decode definition result: %v", err)
		}
		return locations
	}
	t.Fatal("definition request received no response")
	return nil
}

// offsetOf returns the zero-based line and UTF-16 character of the first
// occurrence of a substring, so a test names what it clicks on rather than
// counting columns.
func offsetOf(t *testing.T, source, needle string) (int, int) {
	t.Helper()
	for line, text := range strings.Split(source, "\n") {
		if at := strings.Index(text, needle); at >= 0 {
			return line, len([]rune(text[:at]))
		}
	}
	t.Fatalf("fixture does not contain %q", needle)
	return 0, 0
}

func TestInitializeAdvertisesGoToDefinition(t *testing.T) {
	input := frames(
		`{"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}`,
		`{"jsonrpc":"2.0","id":2,"method":"shutdown"}`,
		`{"jsonrpc":"2.0","method":"exit"}`,
	)
	var output bytes.Buffer
	if err := lsp.Serve(bytes.NewReader(input), &output); err != nil {
		t.Fatalf("serve: %v", err)
	}
	var initialize struct {
		Result struct {
			Capabilities struct {
				DefinitionProvider bool `json:"definitionProvider"`
			} `json:"capabilities"`
		} `json:"result"`
	}
	if err := json.Unmarshal(readFrames(t, output.Bytes())[0], &initialize); err != nil {
		t.Fatalf("decode initialize response: %v", err)
	}
	if !initialize.Result.Capabilities.DefinitionProvider {
		t.Error("initialize did not advertise definitionProvider, so no client registers the feature")
	}
}

func TestDefinitionOpensTheComponentSourceAndNotItsGeneratedFile(t *testing.T) {
	root := filepath.Join(t.TempDir(), "project with spaces")
	writeDefinitionFixture(t, root)

	// Both halves of the call are the same question, and an editor sends
	// whichever one the pointer was over.
	for _, click := range []struct {
		name   string
		needle string
	}{
		{name: "on the package", needle: "components.Button(components"},
		{name: "on the member", needle: "Button(components.ButtonProps"},
	} {
		t.Run(click.name, func(t *testing.T) {
			line, character := offsetOf(t, homeView, click.needle)
			locations := definitionAt(t, root, homeView, line, character+2)
			if len(locations) != 1 {
				t.Fatalf("definition returned %d locations, want 1", len(locations))
			}

			file := pathOf(t, locations[0].URI)
			want := filepath.Join(root, "resources", "views", "components", "button.kyse.go")
			if file != want {
				t.Errorf("definition opened %q, want the editable source %q", file, want)
			}
			if _, err := os.Stat(file); err != nil {
				t.Errorf("definition named a file that does not exist: %v", err)
			}
			// `type ButtonProps` is the seventh line of the source, and the
			// protocol counts from zero. Landing on the props is landing on the
			// component's contract, which is what a caller came to read.
			if got := locations[0].Range.Start.Line; got != 6 {
				t.Errorf("definition landed on line %d, want the props declaration at 6", got)
			}
		})
	}
}

func TestDefinitionOpensTheLayoutNamedByExtends(t *testing.T) {
	root := filepath.Join(t.TempDir(), "project")
	writeDefinitionFixture(t, root)

	line, character := offsetOf(t, homeView, "layouts.app")
	locations := definitionAt(t, root, homeView, line, character+3)
	if len(locations) != 1 {
		t.Fatalf("definition returned %d locations, want the layout", len(locations))
	}
	want := filepath.Join(root, "resources", "views", "layouts", "app.kyse.go")
	if got := pathOf(t, locations[0].URI); got != want {
		t.Errorf("definition opened %q, want %q", got, want)
	}
	if got := locations[0].Range.Start.Line; got != 0 {
		t.Errorf("definition landed on line %d, want the top of the layout", got)
	}
}

// TestDefinitionAnswersNothingRatherThanGuessing is the half of this feature
// that decides whether it is usable.
//
// A wrong location is worse than none: the editor opens a file, the person
// reads it, and nothing anywhere says the answer was invented. Every case below
// is one a plausible implementation gets wrong by looking only at the text.
func TestDefinitionAnswersNothingRatherThanGuessing(t *testing.T) {
	root := filepath.Join(t.TempDir(), "project")
	writeDefinitionFixture(t, root)

	for _, test := range []struct {
		name   string
		text   string
		needle string
		offset int
		why    string
	}{
		{
			name:   "a component the package does not declare",
			text:   strings.Replace(homeView, "components.Button(", "components.Carousel(", 1),
			needle: "components.Carousel",
			offset: 13,
			why:    "the package declares Button and nothing else",
		},
		{
			name:   "a qualifier the view never imported",
			text:   strings.Replace(homeView, "components.Button(", "widgets.Button(", 1),
			needle: "widgets.Button",
			offset: 10,
			why:    "the import block is what says which package a qualifier means",
		},
		{
			name:   "the same call written as prose in the markup",
			text:   homeView,
			needle: "<p>components.Button is written",
			offset: 6,
			why:    "text is text, and a paragraph that mentions a component does not call one",
		},
		{
			name:   "a layout the project does not have",
			text:   strings.Replace(homeView, "layouts.app", "layouts.dashboard", 1),
			needle: "layouts.dashboard",
			offset: 10,
			why:    "resources/views/layouts/dashboard.kyse.go was never written",
		},
		{
			name:   "an unexported name",
			text:   strings.Replace(homeView, "components.Button(", "components.button(", 1),
			needle: "components.button",
			offset: 13,
			why:    "a view cannot reach an unexported declaration at all",
		},
		{
			name:   "a view name that climbs out of the tree",
			text:   strings.Replace(homeView, "layouts.app", "..étc.passwd", 1),
			needle: "..étc.passwd",
			offset: 4,
			why:    "a view name is a path under resources/views and never above it",
		},
		{
			name:   "an HTMX attribute, which is markup and not a symbol",
			text:   strings.Replace(homeView, `<p>components.Button`, `<p hx-get="/rows">components.Button`, 1),
			needle: "hx-get",
			offset: 2,
			why:    "an attribute name is not declared anywhere this server can open",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			line, character := offsetOf(t, test.text, test.needle)
			locations := definitionAt(t, root, test.text, line, character+test.offset)
			if len(locations) != 0 {
				t.Errorf("definition returned %d locations for %s; %s", len(locations), test.needle, test.why)
				for _, at := range locations {
					t.Errorf("    it offered %s:%d", at.URI, at.Range.Start.Line)
				}
			}
		})
	}
}

// TestDefinitionWithoutAWorkspaceRootAnswersNothing fixes what happens when a
// client connects without opening a folder.
//
// The alternative is reading the process's working directory, which is wherever
// the editor happened to be launched from -- so the answers would be about a
// tree nobody chose.
func TestDefinitionWithoutAWorkspaceRootAnswersNothing(t *testing.T) {
	line, character := offsetOf(t, homeView, "components.Button(components")
	input := frames(
		`{"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}`,
		fmt.Sprintf(`{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///doc/home.kyse.go","languageId":"kyse","version":1,"text":%q}}}`, homeView),
		fmt.Sprintf(`{"jsonrpc":"2.0","id":"definition","method":"textDocument/definition","params":{"textDocument":{"uri":"file:///doc/home.kyse.go"},"position":{"line":%d,"character":%d}}}`, line, character+2),
		`{"jsonrpc":"2.0","id":2,"method":"shutdown"}`,
		`{"jsonrpc":"2.0","method":"exit"}`,
	)
	var output bytes.Buffer
	if err := lsp.Serve(bytes.NewReader(input), &output); err != nil {
		t.Fatalf("serve: %v", err)
	}
	for _, body := range readFrames(t, output.Bytes()) {
		var message struct {
			ID     json.RawMessage `json:"id"`
			Result json.RawMessage `json:"result"`
		}
		if err := json.Unmarshal(body, &message); err != nil {
			t.Fatalf("decode response: %v", err)
		}
		if string(message.ID) != `"definition"` {
			continue
		}
		if string(message.Result) != "[]" {
			t.Errorf("definition without a root answered %s, want []", message.Result)
		}
		return
	}
	t.Fatal("definition request received no response")
}

// TestDefinitionResolvesAComponentThroughTheModuleCache covers the arrangement
// every real project has.
//
// The components are imported, not copied, so they live under a version in the
// module cache and not in the tree. Reading the cache directly is what keeps
// this answer off the toolchain: `go list` would have to load the module graph
// on every click.
func TestDefinitionResolvesAComponentThroughTheModuleCache(t *testing.T) {
	base := t.TempDir()
	root := filepath.Join(base, "app")
	cache := filepath.Join(base, "modcache")

	files := map[string]string{
		filepath.Join(root, "go.mod"): `module example.test/app

go 1.26

require example.test/Kyse v1.2.3
`,
		filepath.Join(cache, "example.test", "!kyse@v1.2.3", "components", "button.kyse.go"): buttonSource,
		filepath.Join(cache, "example.test", "!kyse@v1.2.3", "components", "button.go"):      buttonGenerated,
	}
	for path, contents := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("create fixture directory: %v", err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			t.Fatalf("write fixture %s: %v", path, err)
		}
	}
	t.Setenv("GOMODCACHE", cache)

	view := strings.Replace(homeView,
		`import "example.test/app/resources/views/components"`,
		`import "example.test/Kyse/components"`, 1)
	line, character := offsetOf(t, view, "components.Button(components")
	locations := definitionAt(t, root, view, line, character+2)
	if len(locations) != 1 {
		t.Fatalf("definition returned %d locations, want the cached component", len(locations))
	}
	want := filepath.Join(cache, "example.test", "!kyse@v1.2.3", "components", "button.kyse.go")
	if got := pathOf(t, locations[0].URI); got != want {
		t.Errorf("definition opened %q, want %q", got, want)
	}
}

// TestDefinitionSeesAComponentAddedAfterTheFirstAnswer fixes the cache's
// invalidation.
//
// An index that is built once is right until the moment somebody writes a
// component, which is the moment they want to navigate to it. The cache is
// keyed on what the directory's files look like, so writing one is enough to
// drop it.
func TestDefinitionSeesAComponentAddedAfterTheFirstAnswer(t *testing.T) {
	root := filepath.Join(t.TempDir(), "project")
	writeDefinitionFixture(t, root)

	view := strings.Replace(homeView, "components.Button(", "components.Card(", 1)
	line, character := offsetOf(t, view, "components.Card")
	if locations := definitionAt(t, root, view, line, character+13); len(locations) != 0 {
		t.Fatalf("definition found Card before it was written: %v", locations)
	}

	dir := filepath.Join(root, "resources", "views", "components")
	card := strings.ReplaceAll(buttonGenerated, "Button", "Card")
	if err := os.WriteFile(filepath.Join(dir, "card.go"), []byte(card), 0o644); err != nil {
		t.Fatalf("write card: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "card.kyse.go"),
		[]byte(strings.ReplaceAll(buttonSource, "Button", "Card")), 0o644); err != nil {
		t.Fatalf("write card source: %v", err)
	}

	locations := definitionAt(t, root, view, line, character+13)
	if len(locations) != 1 {
		t.Fatalf("definition returned %d locations after the component was written, want 1", len(locations))
	}
	want := filepath.Join(dir, "card.kyse.go")
	if got := pathOf(t, locations[0].URI); got != want {
		t.Errorf("definition opened %q, want %q", got, want)
	}
}

func pathOf(t *testing.T, uri string) string {
	t.Helper()
	parsed, err := url.Parse(uri)
	if err != nil {
		t.Fatalf("parse location URI %q: %v", uri, err)
	}
	if parsed.Scheme != "file" {
		t.Fatalf("location URI %q is not a file URI", uri)
	}
	return filepath.FromSlash(parsed.Path)
}
