package lsp_test

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/arandu-io/aru/internal/lsp"
)

// The component fixture, in the two files a kyse component is written as.
//
// The generated `.go` is the file the compiler reads and the file a naive
// answer would open; the `.kyse.go` beside it is the one a person edits. The
// pair is the whole point of the test: an editor that lands on the generated
// file shows a header saying not to change it.
const (
	buttonSource = `//go:build kyse

package components

@go
// ButtonProps is what a button is drawn from.
type ButtonProps struct {
	Label string
}
@endgo

<button class="btn">{{ .Label }}</button>
`

	buttonGenerated = `// Code generated by ` + "`aru view:build`" + ` from button.kyse.go. DO NOT EDIT.

package components

import kyse__template "html/template"

type ButtonProps struct {
	Label string
}

// Button draws a button.
func Button(kyse__props ButtonProps) kyse__template.HTML {
	return kyse__template.HTML("<button>" + kyse__props.Label + "</button>")
}
`

	layoutSource = `//go:build kyse

package layouts

<html><body>@yield('content')</body></html>
`
)

// homeView is the view every definition test asks from. It imports the
// component package and calls into it exactly the way the skeleton's layout
// does, so the positions below are positions in real markup.
const homeView = `//go:build kyse

package views

import "example.test/app/resources/views/components"

@extends('layouts.app')

@section('content')
	<p>components.Button is written here as prose, not as a call.</p>
	{!! components.Button(components.ButtonProps{Label: "Save"}) !!}
@endsection
`

// homeController is the other half of the round trip a view completes.
//
// A view names a layout and a component; a controller names the view, and it
// names it with a string. Every other position in this file is Go the Go
// language server resolves, and several of them are written to look like the
// one that is not: the same call appears in a doc comment, a package function
// of the same name is called without a receiver, and a string with the view's
// exact spelling is passed to something else.
const homeController = `package controllers

import (
	"errors"

	"example.test/app/resources/views"
)

// Home renders the landing page.
//
// It answers with ctx.View("home", …), which is written on this line as prose
// about the call rather than as the call.
type Home struct {
	title string
}

func (c *Home) Show(ctx *Context) error {
	if c.title == "" {
		return errors.New("home")
	}
	_ = View("home")
	return ctx.View("home", views.HomeData{Title: c.title})
}
`

// assetLinkView writes the two asset references a layout writes, with the
// argument closed: a name being typed is a completion, and a name already
// written is a click.
const assetLinkView = `//go:build kyse

package layouts

<link rel="stylesheet" href="{{ view.Asset("app.css") }}">
<script src="{{ view.Asset("custom.js") }}" defer></script>
<p>A layout writes view.Asset("app.css") here, and here it is prose.</p>
`

func writeDefinitionFixture(t *testing.T, root string) {
	t.Helper()
	files := map[string]string{
		"go.mod": `module example.test/app

go 1.26
`,
		"resources/views/home.kyse.go":              homeView,
		"resources/views/layouts/app.kyse.go":       layoutSource,
		"resources/views/components/button.kyse.go": buttonSource,
		"resources/views/components/button.go":      buttonGenerated,
	}
	for name, contents := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("create fixture directory: %v", err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			t.Fatalf("write fixture %s: %v", name, err)
		}
	}
}

type protocolLocation struct {
	URI   string `json:"uri"`
	Range struct {
		Start struct {
			Line      int `json:"line"`
			Character int `json:"character"`
		} `json:"start"`
	} `json:"range"`
}

// definitionAt drives one go-to-definition over the protocol.
//
// The document is opened with the given text so the request is answered from
// the buffer, which is where an editor's copy lives -- a person navigating from
// an edit they have not saved must not be sent to the file as it was on disk.
func definitionAt(t *testing.T, root, text string, line, character int) []protocolLocation {
	t.Helper()
	return definitionAtURI(t, root, "file:///doc/home.kyse.go", "kyse", text, line, character)
}

// definitionAtURI drives one go-to-definition against a named document.
//
// The name is what the server decides the language from, and it decides two
// different behaviours: a view is parsed as markup and answers about
// components, layouts and assets, while Go source is not parsed at all and
// answers about exactly one string.
func definitionAtURI(t *testing.T, root, uri, languageID, text string, line, character int) []protocolLocation {
	t.Helper()
	rootURI := (&url.URL{Scheme: "file", Path: root}).String()
	input := frames(
		fmt.Sprintf(`{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"rootUri":%q}}`, rootURI),
		fmt.Sprintf(`{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":%q,"languageId":%q,"version":1,"text":%q}}}`, uri, languageID, text),
		fmt.Sprintf(`{"jsonrpc":"2.0","id":"definition","method":"textDocument/definition","params":{"textDocument":{"uri":%q},"position":{"line":%d,"character":%d}}}`, uri, line, character),
		`{"jsonrpc":"2.0","id":2,"method":"shutdown"}`,
		`{"jsonrpc":"2.0","method":"exit"}`,
	)
	var output bytes.Buffer
	if err := lsp.Serve(bytes.NewReader(input), &output); err != nil {
		t.Fatalf("serve: %v", err)
	}
	for _, body := range readFrames(t, output.Bytes()) {
		var message struct {
			ID     json.RawMessage `json:"id"`
			Result json.RawMessage `json:"result"`
			Error  *struct {
				Code    int    `json:"code"`
				Message string `json:"message"`
			} `json:"error"`
		}
		if err := json.Unmarshal(body, &message); err != nil {
			t.Fatalf("decode response: %v", err)
		}
		if string(message.ID) != `"definition"` {
			continue
		}
		if message.Error != nil {
			t.Fatalf("definition answered error %d: %s", message.Error.Code, message.Error.Message)
		}
		var locations []protocolLocation
		if err := json.Unmarshal(message.Result, &locations); err != nil {
			t.Fatalf("decode definition result: %v", err)
		}
		return locations
	}
	t.Fatal("definition request received no response")
	return nil
}

// offsetOf returns the zero-based line and UTF-16 character of the first
// occurrence of a substring, so a test names what it clicks on rather than
// counting columns.
func offsetOf(t *testing.T, source, needle string) (int, int) {
	t.Helper()
	for line, text := range strings.Split(source, "\n") {
		if at := strings.Index(text, needle); at >= 0 {
			return line, len([]rune(text[:at]))
		}
	}
	t.Fatalf("fixture does not contain %q", needle)
	return 0, 0
}

func TestInitializeAdvertisesGoToDefinition(t *testing.T) {
	input := frames(
		`{"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}`,
		`{"jsonrpc":"2.0","id":2,"method":"shutdown"}`,
		`{"jsonrpc":"2.0","method":"exit"}`,
	)
	var output bytes.Buffer
	if err := lsp.Serve(bytes.NewReader(input), &output); err != nil {
		t.Fatalf("serve: %v", err)
	}
	var initialize struct {
		Result struct {
			Capabilities struct {
				DefinitionProvider bool `json:"definitionProvider"`
			} `json:"capabilities"`
		} `json:"result"`
	}
	if err := json.Unmarshal(readFrames(t, output.Bytes())[0], &initialize); err != nil {
		t.Fatalf("decode initialize response: %v", err)
	}
	if !initialize.Result.Capabilities.DefinitionProvider {
		t.Error("initialize did not advertise definitionProvider, so no client registers the feature")
	}
}

func TestDefinitionOpensTheComponentSourceAndNotItsGeneratedFile(t *testing.T) {
	root := filepath.Join(t.TempDir(), "project with spaces")
	writeDefinitionFixture(t, root)

	// Both halves of the call are the same question, and an editor sends
	// whichever one the pointer was over.
	for _, click := range []struct {
		name   string
		needle string
	}{
		{name: "on the package", needle: "components.Button(components"},
		{name: "on the member", needle: "Button(components.ButtonProps"},
	} {
		t.Run(click.name, func(t *testing.T) {
			line, character := offsetOf(t, homeView, click.needle)
			locations := definitionAt(t, root, homeView, line, character+2)
			if len(locations) != 1 {
				t.Fatalf("definition returned %d locations, want 1", len(locations))
			}

			file := pathOf(t, locations[0].URI)
			want := filepath.Join(root, "resources", "views", "components", "button.kyse.go")
			if file != want {
				t.Errorf("definition opened %q, want the editable source %q", file, want)
			}
			if _, err := os.Stat(file); err != nil {
				t.Errorf("definition named a file that does not exist: %v", err)
			}
			// `type ButtonProps` is the seventh line of the source, and the
			// protocol counts from zero. Landing on the props is landing on the
			// component's contract, which is what a caller came to read.
			if got := locations[0].Range.Start.Line; got != 6 {
				t.Errorf("definition landed on line %d, want the props declaration at 6", got)
			}
		})
	}
}

func TestDefinitionOpensTheLayoutNamedByExtends(t *testing.T) {
	root := filepath.Join(t.TempDir(), "project")
	writeDefinitionFixture(t, root)

	line, character := offsetOf(t, homeView, "layouts.app")
	locations := definitionAt(t, root, homeView, line, character+3)
	if len(locations) != 1 {
		t.Fatalf("definition returned %d locations, want the layout", len(locations))
	}
	want := filepath.Join(root, "resources", "views", "layouts", "app.kyse.go")
	if got := pathOf(t, locations[0].URI); got != want {
		t.Errorf("definition opened %q, want %q", got, want)
	}
	if got := locations[0].Range.Start.Line; got != 0 {
		t.Errorf("definition landed on line %d, want the top of the layout", got)
	}
}

// definitionInController drives one go-to-definition against a controller,
// which is Go source and not a view.
func definitionInController(t *testing.T, root, text string, line, character int) []protocolLocation {
	t.Helper()
	return definitionAtURI(t, root, "file:///doc/HomeController.go", "go", text, line, character)
}

// TestDefinitionOpensTheViewAControllerNames is the click this feature exists
// for.
//
// `ctx.View("home", …)` is where a request stops being Go and becomes a page,
// and the string is the only thing in the file that says which page. The Go
// language server resolves the method, the receiver and the data type, and it
// resolves the argument to nothing, because nothing in the type of a string
// says it is a filename.
func TestDefinitionOpensTheViewAControllerNames(t *testing.T) {
	root := filepath.Join(t.TempDir(), "project")
	writeDefinitionFixture(t, root)

	for _, test := range []struct {
		name   string
		text   string
		needle string
		offset int
		want   string
	}{
		{
			name:   "the view beside the data it is rendered with",
			text:   homeController,
			needle: `ctx.View("home", views.HomeData`,
			offset: 12,
			want:   filepath.Join(root, "resources", "views", "home.kyse.go"),
		},
		{
			name:   "a dotted name, which is a path under resources/views",
			text:   strings.Replace(homeController, `ctx.View("home", views.HomeData`, `ctx.View("layouts.app", views.HomeData`, 1),
			needle: `ctx.View("layouts.app"`,
			offset: 13,
			want:   filepath.Join(root, "resources", "views", "layouts", "app.kyse.go"),
		},
		{
			// A call long enough to wrap is the ordinary shape once a page takes
			// more than two fields, and the argument is the same argument.
			name: "a call written across several lines",
			text: strings.Replace(homeController,
				`return ctx.View("home", views.HomeData{Title: c.title})`,
				"return ctx.View(\n\t\t\"home\",\n\t\tviews.HomeData{Title: c.title},\n\t)", 1),
			needle: "\t\t\"home\",",
			offset: 4,
			want:   filepath.Join(root, "resources", "views", "home.kyse.go"),
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			line, character := offsetOf(t, test.text, test.needle)
			locations := definitionInController(t, root, test.text, line, character+test.offset)
			if len(locations) != 1 {
				t.Fatalf("definition returned %d locations, want the view", len(locations))
			}
			if got := pathOf(t, locations[0].URI); got != test.want {
				t.Errorf("definition opened %q, want %q", got, test.want)
			}
			if _, err := os.Stat(test.want); err != nil {
				t.Errorf("definition named a file that does not exist: %v", err)
			}
			if got := locations[0].Range.Start.Line; got != 0 {
				t.Errorf("definition landed on line %d, want the top of the view", got)
			}
		})
	}
}

// TestDefinitionInAControllerAnswersOnlyTheViewName is what keeps this from
// being noise.
//
// Every position below is one the Go language server already answers, and an
// answer offered beside it does not replace it: the editor shows two
// destinations and the person has to decide which server understood their own
// code. So the rule is one string and nothing else, and each case is a way of
// looking like that string without being it.
func TestDefinitionInAControllerAnswersOnlyTheViewName(t *testing.T) {
	root := filepath.Join(t.TempDir(), "project")
	writeDefinitionFixture(t, root)

	for _, test := range []struct {
		name   string
		text   string
		needle string
		offset int
		why    string
	}{
		{
			name:   "the context the method is called on",
			text:   homeController,
			needle: `ctx.View("home", views.HomeData`,
			offset: 1,
			why:    "a receiver is a value, and the Go language server resolves it",
		},
		{
			name:   "the method itself",
			text:   homeController,
			needle: `ctx.View("home", views.HomeData`,
			offset: 5,
			why:    "View is a method on a type, which is the other server's answer",
		},
		{
			name:   "the type the view is rendered with",
			text:   homeController,
			needle: `views.HomeData{Title`,
			offset: 8,
			why:    "a struct type is declared in Go and resolved as Go",
		},
		{
			name:   "a field of the receiver",
			text:   homeController,
			needle: `Title: c.title}`,
			offset: 9,
			why:    "a field is a field",
		},
		{
			name:   "the declaration of the controller",
			text:   homeController,
			needle: `type Home struct`,
			offset: 6,
			why:    "a type declaration is where the other server sends people already",
		},
		{
			name:   "the same call written in a doc comment",
			text:   homeController,
			needle: `ctx.View("home", …)`,
			offset: 12,
			why:    "a comment is prose, and prose that quotes a call does not make one",
		},
		{
			name:   "a string with the view's spelling passed to something else",
			text:   homeController,
			needle: `errors.New("home")`,
			offset: 14,
			why:    "the argument of errors.New is a message, and it names no file",
		},
		{
			name:   "a call to a function of the same name without a receiver",
			text:   homeController,
			needle: `_ = View("home")`,
			offset: 12,
			why:    "a package function called View is some other function, and where it looks is unknown here",
		},
		{
			name:   "a view the project does not have",
			text:   strings.Replace(homeController, `ctx.View("home", views`, `ctx.View("dashboard", views`, 1),
			needle: `ctx.View("dashboard"`,
			offset: 13,
			why:    "resources/views/dashboard.kyse.go was never written",
		},
		{
			name:   "a view name that climbs out of the tree",
			text:   strings.Replace(homeController, `ctx.View("home", views`, `ctx.View("../../etc/passwd", views`, 1),
			needle: `ctx.View("../../etc/passwd"`,
			offset: 13,
			why:    "a view name is a path under resources/views and never above it",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			line, character := offsetOf(t, test.text, test.needle)
			locations := definitionInController(t, root, test.text, line, character+test.offset)
			if len(locations) != 0 {
				t.Errorf("definition returned %d locations for %s; %s", len(locations), test.needle, test.why)
				for _, at := range locations {
					t.Errorf("    it offered %s:%d", at.URI, at.Range.Start.Line)
				}
			}
		})
	}
}

// TestDefinitionOpensTheAssetNamedByViewURL is the other name a view writes as
// a string.
//
// The two kinds of asset are answered by two different files, and each is the
// file the name is decided in. A framework asset is served exactly as it is
// embedded, so the embedded file is all of it; a registered one is bytes and a
// content type chosen at the call, so the call is where its behaviour lives.
func TestDefinitionOpensTheAssetNamedByViewURL(t *testing.T) {
	root := writeCompletionFixture(t)
	cache := filepath.Join(filepath.Dir(root), "modcache")

	for _, test := range []struct {
		name   string
		needle string
		want   string
		line   int
	}{
		{
			name:   "an asset the project registers",
			needle: `view.Asset("custom.js")`,
			want:   filepath.Join(root, "resources", "js", "js.go"),
			// The RegisterAsset call is the sixth line of the fixture and the
			// protocol counts from zero. The line is the point: it is where the
			// content type and the bytes are decided.
			line: 5,
		},
		{
			name:   "an asset the framework embeds",
			needle: `view.Asset("app.css")`,
			want:   filepath.Join(cache, "github.com", "arandu-io", "hesape@v1.0.0", "view", "assets", "app.css"),
			line:   0,
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			// The cursor goes just inside the quoted name, and the offset is
			// measured from the needle rather than written as a number. A
			// literal offset encodes the length of the function name, so
			// renaming the call moves the cursor out of the string and the
			// test reports "no definition" for a server that answers -- which
			// is what a literal 12 did when view.URL became view.Asset.
			line, character := offsetOf(t, assetLinkView, test.needle)
			locations := definitionAt(t, root, assetLinkView, line, character+strings.Index(test.needle, `"`)+2)
			if len(locations) != 1 {
				t.Fatalf("definition returned %d locations, want the asset", len(locations))
			}
			if got := pathOf(t, locations[0].URI); got != test.want {
				t.Errorf("definition opened %q, want %q", got, test.want)
			}
			if _, err := os.Stat(test.want); err != nil {
				t.Errorf("definition named a file that does not exist: %v", err)
			}
			if got := locations[0].Range.Start.Line; got != test.line {
				t.Errorf("definition landed on line %d, want %d", got, test.line)
			}
		})
	}
}

// TestAssetDefinitionRefusesANameViewURLWouldRefuse fixes the negative, and it
// is the one that matters more than the positive.
//
// view.URL panics on a name it was not given. A destination invented for such a
// name is evidence that the asset exists, handed to somebody who is about to
// ship a page that will not load.
func TestAssetDefinitionRefusesANameViewURLWouldRefuse(t *testing.T) {
	root := writeCompletionFixture(t)

	for _, test := range []struct {
		name   string
		text   string
		needle string
		offset int
		why    string
	}{
		{
			name:   "a file beside the assets that is not embedded",
			text:   strings.Replace(assetLinkView, `view.Asset("app.css")`, `view.Asset("app.src.css")`, 1),
			needle: `view.Asset("app.src.css")`,
			offset: 12,
			why:    "app.src.css is in the directory and not in the embed directive, so view.URL rejects it",
		},
		{
			name:   "a name nothing registers",
			text:   strings.Replace(assetLinkView, `view.Asset("custom.js")`, `view.Asset("legacy.js")`, 1),
			needle: `view.Asset("legacy.js")`,
			offset: 12,
			why:    "no RegisterAsset call and no embed directive names it",
		},
		{
			name:   "the same call written as prose in the markup",
			text:   assetLinkView,
			needle: `A layout writes view.Asset("app.css")`,
			offset: 28,
			why:    "text is text, and a paragraph that mentions the call does not make one",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			line, character := offsetOf(t, test.text, test.needle)
			locations := definitionAt(t, root, test.text, line, character+test.offset)
			if len(locations) != 0 {
				t.Errorf("definition returned %d locations for %s; %s", len(locations), test.needle, test.why)
				for _, at := range locations {
					t.Errorf("    it offered %s:%d", at.URI, at.Range.Start.Line)
				}
			}
		})
	}
}

// TestDefinitionAnswersNothingRatherThanGuessing is the half of this feature
// that decides whether it is usable.
//
// A wrong location is worse than none: the editor opens a file, the person
// reads it, and nothing anywhere says the answer was invented. Every case below
// is one a plausible implementation gets wrong by looking only at the text.
func TestDefinitionAnswersNothingRatherThanGuessing(t *testing.T) {
	root := filepath.Join(t.TempDir(), "project")
	writeDefinitionFixture(t, root)

	for _, test := range []struct {
		name   string
		text   string
		needle string
		offset int
		why    string
	}{
		{
			name:   "a component the package does not declare",
			text:   strings.Replace(homeView, "components.Button(", "components.Carousel(", 1),
			needle: "components.Carousel",
			offset: 13,
			why:    "the package declares Button and nothing else",
		},
		{
			name:   "a qualifier the view never imported",
			text:   strings.Replace(homeView, "components.Button(", "widgets.Button(", 1),
			needle: "widgets.Button",
			offset: 10,
			why:    "the import block is what says which package a qualifier means",
		},
		{
			name:   "the same call written as prose in the markup",
			text:   homeView,
			needle: "<p>components.Button is written",
			offset: 6,
			why:    "text is text, and a paragraph that mentions a component does not call one",
		},
		{
			name:   "a layout the project does not have",
			text:   strings.Replace(homeView, "layouts.app", "layouts.dashboard", 1),
			needle: "layouts.dashboard",
			offset: 10,
			why:    "resources/views/layouts/dashboard.kyse.go was never written",
		},
		{
			name:   "an unexported name",
			text:   strings.Replace(homeView, "components.Button(", "components.button(", 1),
			needle: "components.button",
			offset: 13,
			why:    "a view cannot reach an unexported declaration at all",
		},
		{
			name:   "a view name that climbs out of the tree",
			text:   strings.Replace(homeView, "layouts.app", "..étc.passwd", 1),
			needle: "..étc.passwd",
			offset: 4,
			why:    "a view name is a path under resources/views and never above it",
		},
		{
			name:   "an HTMX attribute, which is markup and not a symbol",
			text:   strings.Replace(homeView, `<p>components.Button`, `<p hx-get="/rows">components.Button`, 1),
			needle: "hx-get",
			offset: 2,
			why:    "an attribute name is not declared anywhere this server can open",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			line, character := offsetOf(t, test.text, test.needle)
			locations := definitionAt(t, root, test.text, line, character+test.offset)
			if len(locations) != 0 {
				t.Errorf("definition returned %d locations for %s; %s", len(locations), test.needle, test.why)
				for _, at := range locations {
					t.Errorf("    it offered %s:%d", at.URI, at.Range.Start.Line)
				}
			}
		})
	}
}

// TestDefinitionWithoutAWorkspaceRootAnswersNothing fixes what happens when a
// client connects without opening a folder.
//
// The alternative is reading the process's working directory, which is wherever
// the editor happened to be launched from -- so the answers would be about a
// tree nobody chose.
func TestDefinitionWithoutAWorkspaceRootAnswersNothing(t *testing.T) {
	line, character := offsetOf(t, homeView, "components.Button(components")
	input := frames(
		`{"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}`,
		fmt.Sprintf(`{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///doc/home.kyse.go","languageId":"kyse","version":1,"text":%q}}}`, homeView),
		fmt.Sprintf(`{"jsonrpc":"2.0","id":"definition","method":"textDocument/definition","params":{"textDocument":{"uri":"file:///doc/home.kyse.go"},"position":{"line":%d,"character":%d}}}`, line, character+2),
		`{"jsonrpc":"2.0","id":2,"method":"shutdown"}`,
		`{"jsonrpc":"2.0","method":"exit"}`,
	)
	var output bytes.Buffer
	if err := lsp.Serve(bytes.NewReader(input), &output); err != nil {
		t.Fatalf("serve: %v", err)
	}
	for _, body := range readFrames(t, output.Bytes()) {
		var message struct {
			ID     json.RawMessage `json:"id"`
			Result json.RawMessage `json:"result"`
		}
		if err := json.Unmarshal(body, &message); err != nil {
			t.Fatalf("decode response: %v", err)
		}
		if string(message.ID) != `"definition"` {
			continue
		}
		if string(message.Result) != "[]" {
			t.Errorf("definition without a root answered %s, want []", message.Result)
		}
		return
	}
	t.Fatal("definition request received no response")
}

// TestDefinitionResolvesAComponentThroughTheModuleCache covers the arrangement
// every real project has.
//
// The components are imported, not copied, so they live under a version in the
// module cache and not in the tree. Reading the cache directly is what keeps
// this answer off the toolchain: `go list` would have to load the module graph
// on every click.
func TestDefinitionResolvesAComponentThroughTheModuleCache(t *testing.T) {
	base := t.TempDir()
	root := filepath.Join(base, "app")
	cache := filepath.Join(base, "modcache")

	files := map[string]string{
		filepath.Join(root, "go.mod"): `module example.test/app

go 1.26

require example.test/Kyse v1.2.3
`,
		filepath.Join(cache, "example.test", "!kyse@v1.2.3", "components", "button.kyse.go"): buttonSource,
		filepath.Join(cache, "example.test", "!kyse@v1.2.3", "components", "button.go"):      buttonGenerated,
	}
	for path, contents := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("create fixture directory: %v", err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			t.Fatalf("write fixture %s: %v", path, err)
		}
	}
	t.Setenv("GOMODCACHE", cache)

	view := strings.Replace(homeView,
		`import "example.test/app/resources/views/components"`,
		`import "example.test/Kyse/components"`, 1)
	line, character := offsetOf(t, view, "components.Button(components")
	locations := definitionAt(t, root, view, line, character+2)
	if len(locations) != 1 {
		t.Fatalf("definition returned %d locations, want the cached component", len(locations))
	}
	want := filepath.Join(cache, "example.test", "!kyse@v1.2.3", "components", "button.kyse.go")
	if got := pathOf(t, locations[0].URI); got != want {
		t.Errorf("definition opened %q, want %q", got, want)
	}
}

// TestDefinitionSeesAComponentAddedAfterTheFirstAnswer fixes the cache's
// invalidation.
//
// An index that is built once is right until the moment somebody writes a
// component, which is the moment they want to navigate to it. The cache is
// keyed on what the directory's files look like, so writing one is enough to
// drop it.
func TestDefinitionSeesAComponentAddedAfterTheFirstAnswer(t *testing.T) {
	root := filepath.Join(t.TempDir(), "project")
	writeDefinitionFixture(t, root)

	view := strings.Replace(homeView, "components.Button(", "components.Card(", 1)
	line, character := offsetOf(t, view, "components.Card")
	if locations := definitionAt(t, root, view, line, character+13); len(locations) != 0 {
		t.Fatalf("definition found Card before it was written: %v", locations)
	}

	dir := filepath.Join(root, "resources", "views", "components")
	card := strings.ReplaceAll(buttonGenerated, "Button", "Card")
	if err := os.WriteFile(filepath.Join(dir, "card.go"), []byte(card), 0o644); err != nil {
		t.Fatalf("write card: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "card.kyse.go"),
		[]byte(strings.ReplaceAll(buttonSource, "Button", "Card")), 0o644); err != nil {
		t.Fatalf("write card source: %v", err)
	}

	locations := definitionAt(t, root, view, line, character+13)
	if len(locations) != 1 {
		t.Fatalf("definition returned %d locations after the component was written, want 1", len(locations))
	}
	want := filepath.Join(dir, "card.kyse.go")
	if got := pathOf(t, locations[0].URI); got != want {
		t.Errorf("definition opened %q, want %q", got, want)
	}
}

func pathOf(t *testing.T, uri string) string {
	t.Helper()
	parsed, err := url.Parse(uri)
	if err != nil {
		t.Fatalf("parse location URI %q: %v", uri, err)
	}
	if parsed.Scheme != "file" {
		t.Fatalf("location URI %q is not a file URI", uri)
	}
	return filepath.FromSlash(parsed.Path)
}
