// Code generated by `aru view:build` from index.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	kyse__template "html/template"
	kyse__io "io"

	kyse__view "github.com/arandu-io/framework/view"
)

//line internal/doctor/testdata/clean/resources/views/invoices/index.kyse.go:5

// InvoicesIndexData is the data of this page, and only of this page.
type InvoicesIndexData struct {
	Title    string
	Invoices []models.Invoice
}

//line internal/doctor/testdata/clean/storage/framework/views/invoices/index.go:23

func init() {
	kyse__view.Register("internal.doctor.testdata.clean.resources.views.invoices.index", renderInternalDoctorTestdataCleanResourcesViewsInvoicesIndex)
}

// renderInternalDoctorTestdataCleanResourcesViewsInvoicesIndex renders internal.doctor.testdata.clean.resources.views.invoices.index.
func renderInternalDoctorTestdataCleanResourcesViewsInvoicesIndex(kyse__w kyse__io.Writer, kyse__data any) error {
	kyse__d, kyse__ok := kyse__data.(InvoicesIndexData)
	if !kyse__ok {
		return kyse__view.WrongData("internal.doctor.testdata.clean.resources.views.invoices.index", "InvoicesIndexData", kyse__data)
	}
	_ = kyse__d
	d := kyse__d
	_ = d
	kyse__sections := map[string]func(kyse__io.Writer) error{
		"content": func(kyse__w kyse__io.Writer) error {
			var kyse__err error
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t<h1 class=\"text-2xl font-semibold\">")
			}
			if kyse__err == nil {
//line internal/doctor/testdata/clean/resources/views/invoices/index.kyse.go:16
				_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Title)))
//line internal/doctor/testdata/clean/storage/framework/views/invoices/index.go:47
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "</h1>\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t<!-- Which tab is open is client state: it dies on reload without loss and\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t     the server never sees it, so it is the one thing the browser owns. It\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t     is spelled the way the behaviours file reads it -- data- attributes it\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t     dispatches on, and the selected tab in the ARIA the markup carries\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t     anyway. Nothing here is an expression, which is why it survives\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t     script-src 'self'. -->\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t<div data-tabs class=\"mt-4 flex gap-2\" role=\"tablist\">\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<button data-tab=\"all\" role=\"tab\" aria-selected=\"true\" class=\"rounded px-3 py-1\">All</button>\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t<button data-tab=\"overdue\" role=\"tab\" aria-selected=\"false\" class=\"rounded px-3 py-1\">Overdue</button>\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t</div>\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t<ul class=\"mt-4 divide-y\">\n")
			}
//line internal/doctor/testdata/clean/resources/views/invoices/index.kyse.go:30
			for _, invoice := range kyse__d.Invoices {
				_ = invoice
//line internal/doctor/testdata/clean/storage/framework/views/invoices/index.go:94
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<!-- The raw form, used the one way it is entitled to be: a component\n")
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t     is a function returning template.HTML, and what it interpolated\n")
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t     was escaped when it was generated. -->\n")
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t<li class=\"py-2\">")
				}
				if kyse__err == nil {
//line internal/doctor/testdata/clean/resources/views/invoices/index.kyse.go:34
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(invoice.Reference)))
//line internal/doctor/testdata/clean/storage/framework/views/invoices/index.go:110
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "\t\t\t\t")
				}
				if kyse__err == nil {
//line internal/doctor/testdata/clean/resources/views/invoices/index.kyse.go:35
					_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.UnsafeText(components.Badge(components.BadgeProps{Label: invoice.State})))
//line internal/doctor/testdata/clean/storage/framework/views/invoices/index.go:121
				}
				if kyse__err == nil {
					_, kyse__err = kyse__io.WriteString(kyse__w, "</li>\n")
				}
			}
			if kyse__err == nil {
				_, kyse__err = kyse__io.WriteString(kyse__w, "\t</ul>\n")
			}
			return kyse__err
		},
	}
	return kyse__view.RenderInto(kyse__w, "layouts.app", kyse__data, kyse__sections)
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
	_ = kyse__view.UnsafeText
)
