// Code generated by `aru view:build` from row.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	kyse__template "html/template"
	kyse__io "io"

	kyse__view "github.com/arandu-io/hesape/view"
)

//line internal/doctor/testdata/clean/resources/views/invoices/row.kyse.go:5

// InvoiceRowData is one row, rendered as an HTMX fragment.
type InvoiceRowData struct {
	Invoice models.Invoice
}

//line internal/doctor/testdata/clean/storage/framework/views/invoices/row.go:22

func init() {
	kyse__view.Register("internal.doctor.testdata.clean.resources.views.invoices.row", renderInternalDoctorTestdataCleanResourcesViewsInvoicesRow)
}

// renderInternalDoctorTestdataCleanResourcesViewsInvoicesRow renders internal.doctor.testdata.clean.resources.views.invoices.row.
func renderInternalDoctorTestdataCleanResourcesViewsInvoicesRow(kyse__w kyse__io.Writer, kyse__data any) error {
	kyse__d, kyse__ok := kyse__data.(InvoiceRowData)
	if !kyse__ok {
		return kyse__view.WrongData("internal.doctor.testdata.clean.resources.views.invoices.row", "InvoiceRowData", kyse__data)
	}
	_ = kyse__d
	d := kyse__d
	_ = d
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<li class=\"py-2\" id=\"invoice-")
	}
	if kyse__err == nil {
//line internal/doctor/testdata/clean/resources/views/invoices/row.kyse.go:12
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__view.TextAttr(kyse__d.Invoice.ID))
//line internal/doctor/testdata/clean/storage/framework/views/invoices/row.go:47
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\">\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<span class=\"font-medium\">")
	}
	if kyse__err == nil {
//line internal/doctor/testdata/clean/resources/views/invoices/row.kyse.go:13
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Invoice.Reference)))
//line internal/doctor/testdata/clean/storage/framework/views/invoices/row.go:58
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\t<span class=\"text-slate-500\">")
	}
	if kyse__err == nil {
//line internal/doctor/testdata/clean/resources/views/invoices/row.kyse.go:14
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Invoice.Total)))
//line internal/doctor/testdata/clean/storage/framework/views/invoices/row.go:69
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</span>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</li>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	return kyse__err
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
)
