// Code generated by `aru view:build` from report-row.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	kyse__template "html/template"
	kyse__io "io"

	kyse__view "github.com/arandu-io/hesape/view"
)

//line internal/doctor/testdata/gaps/resources/views/partials/report-row.kyse.go:5

// ReportRowData is one row of the listing, answered on its own to the element
// that asked for it.
type ReportRowData struct {
	Title string
}

//line internal/doctor/testdata/gaps/storage/framework/views/partials/report-row.go:23

func init() {
	kyse__view.Register("internal.doctor.testdata.gaps.resources.views.partials.report-row", renderInternalDoctorTestdataGapsResourcesViewsPartialsReportRow)
}

// renderInternalDoctorTestdataGapsResourcesViewsPartialsReportRow renders internal.doctor.testdata.gaps.resources.views.partials.report-row.
func renderInternalDoctorTestdataGapsResourcesViewsPartialsReportRow(kyse__w kyse__io.Writer, kyse__data any) error {
	kyse__d, kyse__ok := kyse__data.(ReportRowData)
	if !kyse__ok {
		return kyse__view.WrongData("internal.doctor.testdata.gaps.resources.views.partials.report-row", "ReportRowData", kyse__data)
	}
	_ = kyse__d
	d := kyse__d
	_ = d
	var kyse__err error
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "<li>")
	}
	if kyse__err == nil {
//line internal/doctor/testdata/gaps/resources/views/partials/report-row.kyse.go:13
		_, kyse__err = kyse__io.WriteString(kyse__w, kyse__template.HTMLEscapeString(kyse__view.Text(kyse__d.Title)))
//line internal/doctor/testdata/gaps/storage/framework/views/partials/report-row.go:48
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "</li>\n")
	}
	if kyse__err == nil {
		_, kyse__err = kyse__io.WriteString(kyse__w, "\n")
	}
	return kyse__err
}

var (
	_ = kyse__template.HTMLEscapeString
	_ = kyse__io.WriteString
	_ = kyse__view.Text
)
