package spec

import (
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// Dir is where a project keeps the specifications it generated from.
//
// One file per module, named after it, committed with the code it produced.
// That is what makes the round trip real: regenerating reads the file, and the
// bytes it produces are the bytes already there.
//
// It is under database/ because a specification is mostly the entity and its
// columns, and that is where the tree already keeps factories, migrations and
// seeders. There is no modules/<name>/ to put it beside.
const Dir = "database/specs"

// Read parses a specification file and validates it.
//
// Parse and validate together, always. A Read that returned an invalid document
// would be an invitation to skip the check, and the whole value of the DSL is
// that a bad spec dies before it becomes code.
func Read(path string) (Module, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		return Module{}, fmt.Errorf("reading %s: %w", path, err)
	}
	return Parse(body, path)
}

// Parse reads a specification from bytes.
func Parse(body []byte, name string) (Module, error) {
	var m Module

	decoder := yaml.NewDecoder(strings.NewReader(string(body)))
	// KnownFields is what turns a typo into an error. Without it,
	// `requried: true` is silently a field that does not exist, and the
	// generated code is missing a NOT NULL nobody asked about -- which is the
	// exact failure mode a schema exists to prevent.
	decoder.KnownFields(true)

	if err := decoder.Decode(&m); err != nil {
		return Module{}, fmt.Errorf("%s is not a valid specification: %w", name, explain(err, body))
	}

	// The decoder stops after the first document, so anything past the next
	// `---` is read by nobody. That is the same failure KnownFields exists to
	// prevent, one level up: a typo in a key is refused, and a whole module was
	// dropped without a word.
	//
	// It is checked before Validate because it is a fault in the shape of the
	// file rather than in a module: what the other errors even apply to changes
	// once the file is split.
	if extra, found := extraDocuments(decoder); found > 0 {
		return Module{}, fmt.Errorf(
			"%s holds %d documents and only the first is read: %s\n\n"+
				"A specification is one module -- the schema declares an object, not a list.\n"+
				"%s\n\n"+
				"Split %s into one file per module and run the command once for each.",
			name, found+1, m.Name, ignored(extra, found), name)
	}

	if err := m.Validate(); err != nil {
		return Module{}, fmt.Errorf("%s: %w", name, err)
	}
	return m, nil
}

// extraDocuments reads what follows the first document, and reports how many
// documents carry something and what they call themselves.
//
// A document that holds nothing is not one of them. A file ending in `---`, or
// in a comment after one, parses as two documents and carries one module;
// refusing it would reject a file whose only fault is a trailing line, which is
// the kind of false refusal that teaches people to distrust the validator.
func extraDocuments(decoder *yaml.Decoder) (names []string, found int) {
	for {
		var node yaml.Node
		if err := decoder.Decode(&node); err != nil {
			// The end of the file is the only clean way out. Anything else is a
			// document that does not parse, which is still a document nobody was
			// going to read -- and stopping here rather than decoding again is
			// what keeps a broken tail from looping.
			if errors.Is(err, io.EOF) {
				return names, found
			}
			return names, found + 1
		}
		if len(node.Content) == 0 || node.Content[0].Tag == "!!null" {
			continue
		}
		found++
		if name := mappingValue(node.Content[0], "name"); name != "" {
			names = append(names, name)
		}
	}
}

// mappingValue returns the value a top-level key of a mapping carries, or the
// empty string when the node is not a mapping or has no such key.
func mappingValue(node *yaml.Node, key string) string {
	if node.Kind != yaml.MappingNode {
		return ""
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			return node.Content[i+1].Value
		}
	}
	return ""
}

// ignored is the sentence naming the modules that would be generated by nobody.
//
// Named where they name themselves, counted where they do not: a document with
// no `name` still has to be accounted for, or the count above and the list below
// disagree and the reader trusts neither.
func ignored(names []string, found int) string {
	switch {
	case len(names) == 0:
		return fmt.Sprintf("The %s past the first would be generated by nobody.",
			plural(found, "document", "documents"))
	case len(names) < found:
		return fmt.Sprintf("The %s past the first would be generated by nobody, among them %s.",
			plural(found, "document", "documents"), strings.Join(names, ", "))
	default:
		return fmt.Sprintf("The %s past the first would be generated by nobody: %s.",
			plural(found, "module", "modules"), strings.Join(names, ", "))
	}
}

// plural picks the spelling for a count.
func plural(n int, one, many string) string {
	if n == 1 {
		return one
	}
	return many
}

// Marshal renders a specification as YAML.
//
// Two-space indent, which is what every YAML example anyone has read uses. A
// file that comes back formatted differently than it went in makes the round
// trip look broken when it is not.
func Marshal(m Module) ([]byte, error) {
	var b strings.Builder
	encoder := yaml.NewEncoder(&b)
	encoder.SetIndent(2)

	if err := encoder.Encode(m); err != nil {
		return nil, fmt.Errorf("rendering the specification: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("rendering the specification: %w", err)
	}
	return []byte(b.String()), nil
}

// explain turns a yaml error into something a person can act on.
//
// The library says `field requried not found in type spec.Field`, which names
// the Go type rather than the file. Anyone reading it is looking at YAML.
func explain(err error, body []byte) error {
	message := err.Error()
	message = strings.ReplaceAll(message, "yaml: unmarshal errors:\n  ", "")
	message = strings.ReplaceAll(message, "in type spec.Module", "at the top level")
	message = strings.ReplaceAll(message, "in type spec.Field", "in a field")

	// The one syntax error people actually hit, and the one whose message says
	// the least. A description is a sentence, sentences carry colons, and an
	// unquoted colon ends the value -- so YAML reads the rest as a nested map.
	//
	// What the library says is "mapping values are not allowed in this context",
	// which names a YAML concept and no action. This names the line, the colon,
	// and the fix.
	if strings.Contains(message, "mapping values are not allowed") {
		if line, text := offendingLine(body, message); text != "" {
			return fmt.Errorf("%s\n\n  line %d: %s\n\nA value containing \": \" has to be quoted, or YAML reads what follows the\ncolon as a nested key. Wrap it:\n\n  description: \"%s\"",
				message, line, text, strings.TrimSpace(afterKey(text)))
		}
	}
	return fmt.Errorf("%s", message)
}

// offendingLine pulls the line number out of a yaml error and returns its text.
func offendingLine(body []byte, message string) (int, string) {
	// The library formats it as "yaml: line N: ...", one-indexed.
	marker := "line "
	i := strings.Index(message, marker)
	if i < 0 {
		return 0, ""
	}
	rest := message[i+len(marker):]
	end := strings.IndexByte(rest, ':')
	if end < 0 {
		return 0, ""
	}

	number := 0
	for _, c := range rest[:end] {
		if c < '0' || c > '9' {
			return 0, ""
		}
		number = number*10 + int(c-'0')
	}

	lines := strings.Split(string(body), "\n")
	if number < 1 || number > len(lines) {
		return 0, ""
	}
	return number, strings.TrimRight(lines[number-1], "\r")
}

// afterKey returns what follows the first "key: " on a line, which is the value
// that needed quoting.
func afterKey(line string) string {
	if _, value, found := strings.Cut(line, ": "); found {
		return value
	}
	return line
}
