// Code generated by `aru view:build` from index.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/hesape/view"
)

//line internal/doctor/testdata/violations/resources/views/billing/index.kyse.go:5

// BillingIndexData is the data of this page.
type BillingIndexData struct {
	Title string
}

//line internal/doctor/testdata/violations/resources/views/billing/index.go:22

func init() {
	view.Register("internal.doctor.testdata.violations.resources.views.billing.index", renderInternalDoctorTestdataViolationsResourcesViewsBillingIndex)
}

// renderInternalDoctorTestdataViolationsResourcesViewsBillingIndex renders internal.doctor.testdata.violations.resources.views.billing.index.
func renderInternalDoctorTestdataViolationsResourcesViewsBillingIndex(w io.Writer, data any) error {
	d, ok := data.(BillingIndexData)
	if !ok {
		return view.WrongData("internal.doctor.testdata.violations.resources.views.billing.index", "BillingIndexData", data)
	}
	_ = d
	var err error
	if err == nil {
		_, err = io.WriteString(w, "<h1>")
	}
	if err == nil {
//line internal/doctor/testdata/violations/resources/views/billing/index.kyse.go:12
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Title)))
//line internal/doctor/testdata/violations/resources/views/billing/index.go:42
	}
	if err == nil {
		_, err = io.WriteString(w, "</h1>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<!-- Violation: Alpine reaching the server. This should be an HTMX fragment --\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "     x-data holds client state, and the moment it fetches, the application has\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "     two ways to load data with two loading states and two places to forget the\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "     CSRF token. -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div x-data=\"{ open: false, invoices: [], async load() { const r = await fetch('/api/invoices'); this.invoices = await r.json() } }\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<button @click=\"open = !open\">Toggle</button>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<!-- This one is fine: open/closed is client-only, ephemeral and invisible to\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "     the server, which is exactly what doc 14 permits. -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<div x-data=\"{ open: false }\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<button @click=\"open = !open\">Menu</button>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</div>\n")
	}
	return err
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
